- configs/bottom_up/higherhrnet/coco/higher_hrnet32_coco_512x512.py
- configs/bottom_up/higherhrnet/coco/higher_hrnet32_coco_640x640.py
- configs/bottom_up/higherhrnet/coco/higher_hrnet48_coco_512x512.py
- configs/top_down/hourglass/coco/hourglass52_coco_256x256.py
- configs/top_down/hrnet/coco/hrnet_w32_coco_384x288.py
- configs/top_down/hrnet/coco/hrnet_w48_coco_256x192.py
- configs/top_down/hrnet/coco/hrnet_w48_coco_384x288.py
- configs/top_down/resnet/coco/res101_coco_256x192.py
- configs/top_down/resnet/coco/res101_coco_384x288.py
- configs/top_down/resnet/coco/res152_coco_256x192.py
- configs/top_down/resnet/coco/res152_coco_384x288.py
- configs/top_down/resnet/coco/res50_coco_256x192.py
- configs/top_down/resnet/coco/res50_coco_256x192_dark.py
- configs/top_down/resnet/coco/res50_coco_384x288.py
- configs/top_down/resnet/coco/res50_coco_384x288_dark.py
- configs/top_down/scnet/coco/scnet101_coco_256x192.py
- configs/top_down/scnet/coco/scnet101_coco_384x288.py
- configs/top_down/scnet/coco/scnet50_coco_256x192.py
- configs/top_down/scnet/coco/scnet50_coco_384x288.py
Fix https://github.com/open-mmlab/mmpose/issues/13
> Add test_pipeline

- mmpose/datasets/datasets/bottom_up/bottom_up_coco.py
- mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
Hi, I just fixed typos in this PR.
> fix typo: "Ap .5" to "AP .5"

- tools/publish_model.py
add tools for publishing a model
> add publish_model

- mmpose/datasets/datasets/top_down/topdown_mpii_dataset.py
- mmpose/datasets/datasets/top_down/topdown_mpii_trb_dataset.py
- mmpose/datasets/datasets/top_down/topdown_onehand10k_dataset.py
- tools/test.py
> metrics -> metric

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- docs/pretrained.md
> update github actions

- configs/top_down/resnet/README.md
- configs/top_down/resnet/onehand10k/res50_onehand10k_256x256.py
- mmpose/core/evaluation/__init__.py
- mmpose/core/evaluation/top_down_eval.py
- mmpose/datasets/datasets/top_down/topdown_onehand10k_dataset.py
- tests/test_evaluation/test_top_down_eval.py
> add epe and auc

- README.md
- docs/index.rst
> make dataset support more prominent

- mmpose/utils/collect_env.py
- tests/test_utils.py
> use mmcv to collect_env

- tests/test_api/test_inference.py
- tests/test_datasets/test_bottom_up_dataset.py
- tests/test_datasets/test_top_down_dataset.py
> add coverage

- docs/data_preparation.md
- docs/getting_started.md
- docs/index.rst
- docs/merge_docs.sh
- docs/model_zoo.md
- docs/pretrained.md
> rearrange docs

- tests/test_pipelines/test_top_down_pipelines.py
add test TopDownGetRandomScaleRotation
> Test transform

- docs/data_preparation.md
> make dataset second level title

- docs/data_preparation.md
- tools/mat2json.py
> add mat2json tools

- configs/top_down/darkpose/README.md
> fix model download link

- mmpose/core/evaluation/__init__.py
- mmpose/core/evaluation/mesh_eval.py
- tests/test_evaluation/test_mesh_eval.py
Add the function of Procrutes Alignment used in 3D joints error evaluation and corresponding test codes.
> Add the function of Procrutes Alignment

- mmpose/core/__init__.py
- mmpose/core/optimizer/__init__.py
- mmpose/core/optimizer/builder.py
- tests/test_optimizer.py
Add the function to bulid optimizers for sub-models in a model. This function is used in adversarial training. The function and test code are copied from mmediting.
> Add build_optimizers

- mmpose/models/losses/__init__.py
- mmpose/models/losses/mesh_loss.py
- tests/test_loss/test_mesh_losses.py
Add mesh loss and gan loss for human mesh estimation.
> Add mesh loss and gan loss for human mesh estimation.

- requirements/runtime.txt
Fix https://github.com/open-mmlab/mmpose/issues/213
> Remove dataclass from dependency

- mmpose/apis/inference.py
- mmpose/datasets/datasets/top_down/topdown_mpii_dataset.py
> add mpii demo

- demo/top_down_img_demo_with_mmdet.py
- demo/top_down_video_demo_with_mmdet.py
> support different return formats of mmdet

- mmpose/models/backbones/base_backbone.py
- mmpose/models/backbones/cpm.py
- mmpose/models/backbones/hourglass.py
- mmpose/models/detectors/base.py
> Deleted unnecessary-pass。

- mmpose/apis/test.py
- mmpose/core/evaluation/eval_hooks.py
- mmpose/core/fp16/utils.py
- mmpose/core/optimizer/builder.py
- mmpose/datasets/datasets/bottom_up/bottom_up_base_dataset.py
- mmpose/models/backbones/mobilenet_v2.py
- mmpose/models/backbones/mobilenet_v3.py
- mmpose/models/backbones/regnet.py
- mmpose/models/backbones/resnet.py
- mmpose/models/backbones/shufflenet_v1.py
- mmpose/models/backbones/shufflenet_v2.py
- mmpose/models/backbones/utils/inverted_residual.py
- mmpose/models/builder.py
- mmpose/models/detectors/bottom_up.py
- mmpose/models/detectors/mesh.py
- mmpose/models/detectors/top_down.py
- mmpose/models/losses/mesh_loss.py
- mmpose/models/losses/multi_loss_factory.py
> no-else-return.

- mmpose/models/detectors/base.py
> rm unused method

- mmpose/models/detectors/bottom_up.py
- mmpose/models/detectors/mesh.py
- mmpose/models/detectors/top_down.py
- tests/test_model/test_bottom_up_forward.py
- tests/test_model/test_mesh_forward.py
- tests/test_model/test_top_down_forward.py
useful for get_flops & export_onnx
> Add dummy forward function

- README.md
> Added pypi badge in readme.

- configs/top_down/resnet/aic/res101_aic_256x192.py
- configs/top_down/resnet/aic/res101_aic_384x288.py
- configs/top_down/resnet/aic/res152_aic_256x192.py
- configs/top_down/resnet/aic/res152_aic_384x288.py
- configs/top_down/resnet/aic/res50_aic_256x192.py
- configs/top_down/resnet/aic/res50_aic_384x288.py
Correct val_pipeline in aic datasets configs.
> Correct topdown aic configs

- docs/stat.py
- mmpose/models/backbones/mspn.py
- mmpose/models/backbones/rsn.py
> Fix paper regex

- configs/top_down/mspn/coco/2xmspn50_coco_256x192.py
- configs/top_down/mspn/coco/3xmspn50_coco_256x192.py
- configs/top_down/mspn/coco/4xmspn50_coco_256x192.py
- configs/top_down/mspn/coco/mspn50_coco_256x192.py
Remove' bbox_id' in mspn configs
> rm bbox_id in mspn configs

- configs/bottom_up/udp/README.md
- configs/bottom_up/udp/coco/higher_hrnet32_coco_512x512_udp.py
- configs/bottom_up/udp/coco/hrnet_w32_coco_512x512_udp.py
- configs/top_down/cpm/jhmdb/cpm_jhmdb_sub1_368x368.py
- configs/top_down/cpm/jhmdb/cpm_jhmdb_sub2_368x368.py
- configs/top_down/cpm/jhmdb/cpm_jhmdb_sub3_368x368.py
- configs/top_down/resnet/jhmdb/res50_2deconv_jhmdb_sub1_256x256.py
- configs/top_down/resnet/jhmdb/res50_2deconv_jhmdb_sub2_256x256.py
- configs/top_down/resnet/jhmdb/res50_2deconv_jhmdb_sub3_256x256.py
- configs/top_down/resnet/jhmdb/res50_jhmdb_sub1_256x256.py
- configs/top_down/resnet/jhmdb/res50_jhmdb_sub2_256x256.py
- configs/top_down/resnet/jhmdb/res50_jhmdb_sub3_256x256.py
- configs/top_down/udp/README.md
- configs/top_down/udp/coco/hrnet_w32_coco_256x192_udp.py
- configs/top_down/udp/coco/hrnet_w32_coco_256x192_udp_regress.py
- demo/2d_hand_demo.md
- demo/2d_human_pose_demo.md
- demo/2d_pose_tracking_demo.md
- docs/faq.md
- tests/test_model/test_mesh_forward.py
- tests/test_model/test_top_down_forward.py
1. add ckpts for udp
2. update some deprecated variables in the config files
3. rename the configs: `udp` to `udp_regress`
4. rename the configs: `udp_GaussianHeatMap` to `udp`
> Add udp ckpts and update configs

- configs/bottom_up/higherhrnet/README.md
- configs/bottom_up/hrnet/README.md
- configs/bottom_up/mobilenet/README.md
- configs/bottom_up/resnet/README.md
- configs/bottom_up/udp/README.md
- configs/hand/mobilenet_v2/README.md
- configs/hand/resnet/README.md
- configs/mesh/hmr/README.md
- configs/top_down/alexnet/README.md
- configs/top_down/cpm/README.md
- configs/top_down/darkpose/README.md
- configs/top_down/hourglass/README.md
- configs/top_down/hrnet/README.md
- configs/top_down/mobilenet_v2/README.md
- configs/top_down/mspn/README.md
- configs/top_down/resnest/README.md
- configs/top_down/resnet/README.md
- configs/top_down/resnetv1d/README.md
- configs/top_down/resnext/README.md
- configs/top_down/rsn/README.md
- configs/top_down/scnet/README.md
- configs/top_down/seresnet/README.md
- configs/top_down/shufflenet_v1/README.md
- configs/top_down/shufflenet_v2/README.md
- configs/top_down/udp/README.md
- configs/top_down/vgg/README.md
> Annotate paper types

- docs/stat.py
> Add paper link

- README.md
- docs/index.rst
- docs/stat.py
- docs/tasks/3d_body_mesh.md
> dataset stats

- docs/stat.py
> Cross reference

- docs/tasks/2d_body_keypoint.md
> add image_info for test-dev

- mmpose/apis/train.py
> fix a bug in apis/train.py

- docs/index.rst
> Fix fashion doc

- README.md
> add expand/collapse

- README.md
- README_CN.md
> add deeppose to readme

- mmpose/datasets/builder.py
- mmpose/datasets/samplers/distributed_sampler.py
> add seed option

- mmpose/datasets/pipelines/top_down_transform.py
> fix num_factors

- demo/2d_face_demo.md
- demo/2d_hand_demo.md
- demo/2d_human_pose_demo.md
- demo/2d_pose_tracking_demo.md
- demo/2d_wholebody_pose_demo.md
> Try gif everywhere

- demo/2d_human_pose_demo.md
- demo/2d_pose_tracking_demo.md
- demo/2d_wholebody_pose_demo.md
- docs/faq.md
> add links to mmdet and mmtrack

- docs/install.md
> Doc install

- mmpose/models/backbones/__init__.py
- mmpose/models/backbones/tcn.py
- tests/test_backbones/test_tcn.py
add TCN backbone for 3D pose estimation
> add TCN backbone

- mmpose/core/evaluation/bottom_up_eval.py
- mmpose/core/post_processing/__init__.py
- mmpose/core/post_processing/post_transforms.py
- mmpose/datasets/pipelines/bottom_up_transform.py
- mmpose/datasets/pipelines/top_down_transform.py
* move functions get_warp_matrix and warp_affine_joints into core
> Fix circular importing

- mmpose/models/backbones/tcn.py
- tests/test_backbones/test_tcn.py
"train_with_stride_conv" --> "use_stride_conv"
> modify option name in TCN

- configs/body3d/simple_baseline/h36m/linear_h36m_block2x1024_maxnorm.py
- mmpose/core/evaluation/eval_hooks.py
- mmpose/core/evaluation/pose3d_eval.py
- mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py
- tests/test_datasets/test_body3d_dataset.py
* Add n-mpjpe metric
* Remove align_root option. Always relativize the prediction and the groundtruth instead.
* Refactor keypoint_mpjpe function
> Update H36M 3d keypoint evaluation metrics

- mmpose/apis/inference.py
> fix empty person results

- configs/body3d/simple_baseline/h36m/linear_h36m_block2x1024_maxnorm.py
- mmpose/datasets/datasets/body3d/body3d_h36m_dataset.py
- mmpose/datasets/pipelines/pose3d_transform.py
- mmpose/models/keypoint_heads/temporal_regression_head.py
- tests/test_model/test_pose_lifter_forward.py
- tests/test_model/test_temporal_regression_head.py
This is to support all evaluation protocols in videopose3d.
> Refactor 3d head

- mmpose/datasets/datasets/bottom_up/bottom_up_coco.py
- mmpose/datasets/pipelines/bottom_up_transform.py
- mmpose/datasets/pipelines/top_down_transform.py
- tests/test_pipelines/test_bottom_up_pipelines.py
> add PAF pipeline

- demo/bottom_up_img_demo.py
- demo/bottom_up_pose_tracking_demo.py
- demo/bottom_up_video_demo.py
- demo/docs/2d_human_pose_demo.md
- demo/docs/2d_pose_tracking_demo.md
- demo/top_down_img_demo_with_mmdet.py
- demo/top_down_pose_tracking_demo_with_mmdet.py
- demo/top_down_video_demo_with_mmdet.py
- mmpose/apis/inference.py
- mmpose/apis/inference_tracking.py
- mmpose/datasets/datasets/bottom_up/bottom_up_base_dataset.py
- mmpose/datasets/datasets/bottom_up/bottom_up_coco.py
- mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
- mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py
- tests/test_api/test_inference.py
- tests/test_api/test_inference_tracking.py
- tests/test_datasets/test_bottom_up_dataset.py
add nms for bottom up dataset and demo.
> Bottomup nms

- mmpose/apis/inference.py
Let user define radius of keypoint and thickness of line for visualization in vis_pose_result function
> add radius, thickness parameters in vis_pose_result()

- MANIFEST.in
- configs/top_down/hrnet/metafile.yml
- configs/top_down/resnet/metafile.yml
- model_zoo.yml
- requirements/mminstall.txt
- setup.py
- add MANIFEST.in
- add metafile for 2 topdown models (resnet, hrnet)
- add model_zoo.yml
- add mminstall.txt
- modify setup.py
> Support mmcli

- mmpose/core/visualization/image.py
> Fix image.py

- requirements/optional.txt
- requirements/runtime.txt
Reverts open-mmlab/mmpose#676
This seems to cause an error when publish mmpose to pypi
> Revert "Fix dependency"

- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/h36m/hrnet_w32_h36m_256x256.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/h36m/hrnet_w48_h36m_256x256.py
- mmpose/apis/inference.py
- mmpose/datasets/datasets/__init__.py
- mmpose/datasets/datasets/top_down/__init__.py
- mmpose/datasets/datasets/top_down/topdown_h36m_dataset.py
- tests/test_datasets/test_top_down_dataset.py
* add TopDownH36MDataset
* support human3.6m 2d keypoint  inference
* add experiment configs
> Add H36M dataset for 2D keypoint detection

- tools/dataset/h36m_to_coco.py
- tools/dataset/preprocess_h36m.py
* Convert focal length "f" unit from mm to m
* Fix docstring in h36m_to_coco.py
> Fix h36m preproc

- tools/dataset/h36m_to_coco.py
- tools/dataset/preprocess_h36m.py
> Revert "Fix h36m preproc"

- configs/hand/3d_kpt_sview_rgb_img/internet/interhand3d/res50_interhand3d_all_256x256.py
- demo/README.md
- demo/docs/3d_hand_demo.md
- demo/interhand3d_img_demo.py
- mmpose/apis/__init__.py
- mmpose/apis/inference_3d.py
- mmpose/core/camera/single_camera.py
- mmpose/core/visualization/image.py
- mmpose/models/detectors/interhand_3d.py
- tests/test_api/test_inference_3d.py
- tests/test_pipelines/test_pose3d_transform.py
Add demo for interhand 3d task.
> Interhand3d demo

- configs/_base_/datasets/mpi_inf_3dhp.py
Add `configs/_base_/datasets/mpi_inf_3dhp.py`
> Add datase_info for mpi_inf_3dhp

- mmpose/datasets/datasets/mesh/mesh_mix_dataset.py
refactor MeshMixDataset with WeightedRandomSampler and add more comments.
> MeshMixDataset

- MANIFEST.in
`mmpose/model_zoo.yml` -> `mmpose/model-index.yml`
> Modify MANIFEST.in

- mmpose/__init__.py
- mmpose/version.py
- requirements/mminstall.txt
* update minimum mmcv version requirement to 1.3.8
> Bump version to 0.16.0

- README.md
- README_CN.md
* edited the cover of the demo video
> Update README video

- mmpose/datasets/builder.py
> update resource limit

- mmpose/core/visualization/image.py
- requirements/optional.txt
- tests/test_visualization.py
* update imshow_bbox to handle empty bboxes to fix #795 
* update unittest
* add trimesh into requirements (related to #771)
> Fix imshow_bbox error when input bboxes is empty

- README.md
- README_CN.md
- demo/docs/webcam_demo.md
- demo/webcam_demo.py
* Add LiteHRNet into README.md and README_CN.md
* Minor fix to webcam_demo.py
> Add LiteHRNet into README.md

- mmpose/models/backbones/shufflenet_v1.py
Fix docstring and init_weights error of ShuffleNetV1.
> [Fix ] Fix docstring and init_weights error of ShuffleNetV1

- docs/install.md
- docs_zh-CN/install.md
The followings are not checked very carefully.  
1. installation via mim   
2. installation on MacOS
3. Docker
> Translate install

- docs/getting_started.md
- docs_zh-CN/getting_started.md
1. Fix some errors in the docs.
2. Translate it into Chinese.
> Translate getting started

- docs/getting_started.md
Fix linting error involved in #805
> Fix linting of getting_started.md

- docs/changelog.md
1. Update the changelog. I only collect those already-merged PRs.
2. Add the contributor/author.
> update changelog v0.17.0

- tests/test_loss/test_classification_loss.py
- tests/test_loss/test_regression_losses.py
This PR is used to test default weight 'None' in loss_classification and loss_regression unitly.
> Add unittest for None loss weight

- .readthedocs.yml
refer to: https://github.com/open-mmlab/mmdetection/pull/5738/files
> Update readthedocs settings to support pdf/epub export

- docs/tasks/2d_face_keypoint.md
Seems that the annotation files is redundant, so I'm removing them.
> Correct dataset preparation guide of WFLW

- configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/resnet_horse10.md
- configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/horse10/resnet_horse10.yml
- configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_udp_rhd2d.md
- configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_udp_rhd2d.yml
- configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/resnet_rhd2d.md
- configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/resnet_rhd2d.yml
Please describe the motivation of this PR and the goal you want to achieve through this PR.
Please briefly describe what modification is made in this PR.
Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before …
> fix typos in configs

- .github/workflows/build.yml
- setup.py
Add python3.8 in CI
* Add py3.9 in build.yml
* Modify build.yml to upload codecov only for python3.7 && pytorch1.6
* update setup.py
**Before PR**:
**After PR**:
> Add python3.9 in CI

- .dev_scripts/benchmark/benchmark_cfg.yaml
- .dev_scripts/benchmark/benchmark_regression_cfg_tmpl.yaml
Add model list for benchmark regression.
Add .dev_scripts/benchmark/benchmark_cfg.yaml
Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before PR**:
**After PR**:
> Update the model list for benchmark regression

- demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py
- requirements/mminstall.txt
Fix #888 caused by the out-of-date mmtrack config.
- update `demo/mmtracking_cfg/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py`
- update dependency to `mmtrack>=v0.6.0` and `mmdet>=v2.14.0`
**Before PR**:
**After PR**:
> Update mmtrack config and version dependency

- mmpose/core/evaluation/top_down_eval.py
- mmpose/models/heads/interhand_3d_head.py
Fix the bug in [issues 879](https://github.com/open-mmlab/mmpose/issues/879).
> fix a bug in the get_accuracy function of interhand_3d_head

- requirements/docs.txt
Fix version of readthedocs dependencies. See also https://github.com/open-mmlab/mmdetection/pull/6005.
requirements/docs.txt
> Fix version of readthedocs dependencies

- demo/bottom_up_img_demo.py
- demo/docs/2d_human_pose_demo.md
Simplify arguments of `demo/bottom_up_img_demo.py` and remove the coco dependency.
**Before PR**:
**After PR**:
> Remove coco dependency from bottom_up_img_demo.py

- docs/tasks/2d_hand_keypoint.md
- docs/tasks/3d_hand_keypoint.md
- mmpose/apis/inference.py
Update the link of interhand annotation. Fix a bug in LoadImage function.
Modify the link of interhand annotation. 
Change the process of LoadImage when the input is np.array and channel_order  is not 'rgb'.
**Before PR**:
- [Y] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) to create this PR.
- [Y] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmpose/blob/master/.github/CONTRIBUTING.md) …
> Update the link of interhand annotation. Fix a bug in LoadImage function.

- mmpose/apis/train.py
- tools/test.py
Fix #923 
Related PRs: https://github.com/open-mmlab/mmocr/pull/459
Follow https://github.com/open-mmlab/mmocr/blob/main/mmocr/apis/train.py to refactor the collection of the config for training/testing.
**Before PR**:
**After PR**:
> [Feature] Support multiple settings for data_loader

- mmpose/apis/train.py
- tools/test.py
> Revert "[Feature] Support multiple settings for data_loader"

- mmpose/models/builder.py
#669 did not use mmcv's MODELS registry as root/parent registry. This makes it impossible to build models across projects.
mmpose/models/builder.py
```Python
from mmcv.cnn import MODELS as MMCV_MODELS
from mmcv.cnn import build_model_from_cfg
from mmcv.utils import Registry
MODELS = Registry(
'models', build_func=build_model_from_cfg, parent=MMCV_MODELS)
```
None.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before PR**:
**After PR**:
> [Fix]: Use mmcv root model registry.

- configs/_base_/datasets/h36m.py
Fix error in [h36m](https://github.com/open-mmlab/mmpose/blob/dfa55ec69f7c585c97698aa949229ecead01c502/configs/_base_/datasets/h36m.py).
Modify the h36m keypoint indexes.
> [Fix] fix h36m keypoint index in dataset info

- docs/install.md
For some reason, `git clone git@github.com:open-mmlab/mmpose.git` may return 
```
Cloning into 'mmpose'...
The authenticity of host 'github.com (15.164.81.167)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
Therefore, `git clone https://github.com/open-mmlab/mmpose` can be run
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from …
> [Fix] Add command to clone mmpose via https in the docs

- tools/dataset/parse_macaquepose_dataset.py
fix #947 
Fix a bug in parsing segmentation
parse_macaquepose_dataset.py
**Before PR**:
**After PR**:
> [Fix] fix parsing segmentation

- docs/changelog.md
- mmpose/version.py
Bump version to v0.20.0
- `mmpose/version.py`
- `docs/changelog.md`
**Before PR**:
**After PR**:
> Bump version to v0.20.0

- mmpose/apis/inference.py
Refer to https://github.com/open-mmlab/mmdetection/pull/6405
**Before PR**:
**After PR**:
> [Fix] Always map location to cpu when load checkpoint

- .dev_scripts/benchmark/benchmark_cfg.yaml
- .dev_scripts/benchmark/dummy_dataset_cfg.yaml
- .dev_scripts/benchmark/flops_test.py
- .dev_scripts/benchmark/speed_test.py
- .dev_scripts/inference_speed/speed_test.py
Add the tools to calculate the inference speed and flops of multiple models at once.
Fix some typos in benchmark_cfg.yaml file.
> [Enhancement] inference speed and flops tools.

- configs/_base_/datasets/coco_wholebody.py
The root keypoints of hands have been renamed from ``left/right_wrist`` (which is reduplicate) to ``left/right_hand_root``. However, the skeleton_info has not been updated. This PR fixes it and connects skeletons correctly.
**Before PR**:
**After PR**:
> [Fix] fix skeleton_info of coco wholebody dataset

- README.md
- README_CN.md
- docs/conf.py
- docs_zh-CN/conf.py
Add MMFlow descriptions and links in README and doc pages.
**Before PR**:
**After PR**:
> [Enhance] Add mmflow reference in README and docs

- README.md
- README_CN.md
- docs/conf.py
- docs_zh-CN/conf.py
> [Doc] Add mmfewshot link in README and docs

- configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hourglass_ae_coco.md
- configs/body/2d_kpt_sview_rgb_img/associative_embedding/coco/hourglass_ae_coco.yml
update hourglass ae .md
**Before PR**:
**After PR**:
> update hourglass ae .md

- .pre-commit-config.yaml
- configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_coco-wholebody.yml
- configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/vipnas_dark_coco-wholebody.yml
- mmpose/apis/__init__.py
- mmpose/apis/train.py
- tools/train.py
Follow https://github.com/open-mmlab/mmdetection/pull/6457
- When the seed is not set in the args, it will randomly generate a seed and broadcast to all ranks.
**Before PR**:
**After PR**:
> [Enhancement] Set a random seed when the user does not set a seed

- .dev_scripts/benchmark/benchmark_cfg_flops_speed.yaml
- .dev_scripts/benchmark/speed_test.py
Modify the speed test script to make it more flexible.
Modify the model list file for flops and speed benchmark.
1. Add the batch size and device args, to support running a speed test on both CPU and GPU with adjustable batch size.
2. Remove the `MMDataParallel` warper and modify the output from dataloader accordingly.
3. Record both the speed and its standard deviation to check if the speed test script is running normally.
4. Modify the model list file, to support running large batch size for topdown models.
**Before PR**:
**After PR**:
> [Enhancement] Add more functions for speed test tool

- configs/_base_/datasets/ap10k.py
Fix #987 
**Before PR**:
**After PR**:
> [Fix] Fix ap10k sigmas

- .github/workflows/build.yml
> [Fix] cancel uncompleted previous runs

- mmpose/__init__.py
> [Fix] Update mmcv maximum version

- README.md
- README_CN.md
- docs/conf.py
- docs_zh-CN/conf.py
> [Doc] Add mmhuman3d reference

- demo/docs/3d_body_mesh_demo.md
> [Fix] Correct docs for 3D mesh demo

- docs_zh-CN/conf.py
> [Fix] Use en doc link for repos whose cn doc is not ready

- .github/workflows/build.yml
> [Fix] Fix path-ignore in workflow build

- configs/body/2d_kpt_sview_rgb_vid/posewarper/posetrack18/hrnet_posetrack18_posewarper.md
Add description about `val_boxes` path for data preparation.
Modify `configs/body/2d_kpt_sview_rgb_vid/posewarper/posetrack18/hrnet_posetrack18_posewarper.md
`. 
**Before PR**:
**After PR**:
> [Doc] Add description about `val_boxes` path for data preparation

- docs/changelog.md
- mmpose/version.py
> Bump version to v0.21.0

- docs_zh-CN/conf.py
> [Fix] fix mmgeneration link in docs_zh-CN/conf.py

- mmpose/apis/inference.py
- tests/test_apis/test_inference.py
> [Fix] Fix bottom up inference demo on coco-wholebody dataset

- docs/en/papers/datasets/ap10k.md
> [Fix] Fix inconsistent AP-10K references that causes errors of stats in docs

- tests/test_utils.py
Fix the unit test of StopWatch by using larger `rtol` arguments.
**Before PR**:
**After PR**:
> [Fix] Fix StopWatch unit test 

- README.md
- README_CN.md
> [Doc] add MMSelfSup and MMRazor links

- docs/changelog.md
- mmpose/version.py
update changelog and __version__
**Before PR**:
**After PR**:
> Bump version to v0.22.0

- mmpose/models/backbones/mobilenet_v3.py
- mmpose/models/backbones/vipnas_mbv3.py
Default hsigmoid parameters in mmcv.ConvModule will be changed in https://github.com/open-mmlab/mmcv/pull/1622. This PR manually sets these parameters in configs to avoid changing of model accuracy.
**Before PR**:
**After PR**:
> [Fix] manually set hsigmoid params

- tools/webcam/configs/examples/README.md
- tools/webcam/configs/examples/pose_estimation.py
- tools/webcam/configs/examples/test_camera.py
- tools/webcam/configs/eyes/README.md
- tools/webcam/configs/eyes/eyes.py
- tools/webcam/webcam_apis/nodes/frame_effect_nodes.py
> [WebcamAPI] Add demo README

- docs/zh_cn/getting_started.md
fix bug
**Before PR**:
**After PR**:
> [Doc] Update zh_cn/getting_started.md

- docs/en/install.md
fix bugs
**Before PR**:
**After PR**:
> [Doc] Update install.md

- docs/en/tutorials/1_finetune.md
fix #1151
**Before PR**:
**After PR**:
> [Doc] Fix typo in 1_finetune.md

- mmpose/core/visualization/__init__.py
- mmpose/core/visualization/effects.py
- tools/webcam/configs/newyear/README.md
- tools/webcam/configs/newyear/new_year.py
- tools/webcam/webcam_apis/nodes/frame_effect_nodes.py
Create a new year webdemo with new year hat and firecracker effects.
**Before PR**:
**After PR**:
> [WebcamAPI] Newyear2

- docs/en/getting_started.md
- docs/zh_cn/getting_started.md
- mmpose/apis/train.py
Refer to https://github.com/open-mmlab/mmdetection/pull/7016
**Before PR**:
**After PR**:
> [Feature] Support CPU train/test

- configs/body/3d_kpt_mview_rgb_img/README.md
Fix #1166 
**Before PR**:
**After PR**:
> [Fix] incorrect paths in README.md

- docs/en/tutorials/2_new_dataset.md
- docs/zh_cn/tutorials/2_new_dataset.md
> [Docs] docs about adding custom datasets

- configs/_base_/default_runtime.py
- mmpose/utils/__init__.py
- mmpose/utils/setup_env.py
- tests/test_utils.py
- tools/test.py
- tools/train.py
Refer to https://github.com/open-mmlab/mmdetection/pull/7036
**Before PR**:
**After PR**:
> [Feature] Add setup multi-processing both in train and test

- tools/webcam/configs/background/README.md
- tools/webcam/configs/examples/README.md
- tools/webcam/configs/examples/pose_estimation.py
- tools/webcam/configs/meow_dwen_dwen/meow_dwen_dwen.py
- tools/webcam/configs/newyear/new_year.py
- tools/webcam/configs/supersaiyan/README.md
- tools/webcam/run_webcam.py
- tools/webcam/webcam_apis/nodes/frame_effect_nodes.py
- tools/webcam/webcam_apis/nodes/xdwendwen_nodes.py
- tools/webcam/webcam_apis/webcam_runner.py
* add rigid transform
* update configs and readme files
**Before PR**:
**After PR**:
> [WebcamAPI] Update XDwenDwen example

- .pre-commit-config.yaml
- setup.cfg
- setup.py
- tests/test_apis/test_inference_3d.py
- tests/test_backward_compatibility/test_dataset_info_compatibility/test_animal_dataset_compatibility.py
- tests/test_backward_compatibility/test_dataset_info_compatibility/test_face_dataset_compatibility.py
- tests/test_backward_compatibility/test_dataset_info_compatibility/test_fashion_dataset_compatibility.py
- tests/test_backward_compatibility/test_dataset_info_compatibility/test_hand_dataset_compatibility.py
- tests/test_backward_compatibility/test_dataset_info_compatibility/test_top_down_dataset_compatibility.py
- tests/test_backward_compatibility/test_registry_compatibility.py
- tests/test_config.py
- tests/test_datasets/test_animal_dataset.py
- tests/test_datasets/test_face_dataset.py
- tests/test_datasets/test_fashion_dataset.py
- tests/test_datasets/test_hand_dataset.py
- tests/test_datasets/test_top_down_dataset.py
- tests/test_external/test_smpl.py
- tests/test_models/test_mesh_forward.py
- tests/test_onnx.py
Related PR: https://github.com/open-mmlab/mmflow/pull/87
Upgrade the version of isort.
1. Remove `seed-isort-config` in pre-commit hook
2. Upgrade `isort` to v5.10.1 (latest version)
3. Replace `known_standard_library` with `extra_standard_library`
4. Change import orders  resulting from upgrading isort
**Before PR**:
**After PR**:
> [Enhancement] Upgrade isort in pre-commit hook

- tools/webcam/run_webcam.py
- tools/webcam/webcam_apis/nodes/frame_effect_nodes.py
> [Fix] Fix webcam demo default config

- README.md
- README_CN.md
- docs/en/changelog.md
- mmpose/version.py
> Bump version v0.23.0

- README.md
> [Fix] Fix readme typo

- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub1_368x368.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub2_368x368.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/cpm_jhmdb_sub3_368x368.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub1_256x256.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub2_256x256.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_2deconv_jhmdb_sub3_256x256.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub1_256x256.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub2_256x256.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/jhmdb/res50_jhmdb_sub3_256x256.py
Fix #1186 
**Before PR**:
**After PR**:
> [Fix] jhmdb config

- mmpose/core/distributed_wrapper.py
Register DistributedDataParallelWrapper in mmpose to a separate registry whose parent is the MODULE_WRAPPERS registry in mmcv. This avoids scope collision with other codebases.
**Before PR**:
**After PR**:
> [Fix] Fix module wrappers registry

- .github/workflows/build.yml
- docs/en/install.md
- docs/zh_cn/install.md
> [Fix] Update mmcv installation CI and doc

- README.md
- README_CN.md
- Add MMRotate reference
- Organize repo information
**Before PR**:
**After PR**:
> [Docs] update OpenMMLab repo information

- configs/animal/2d_kpt_sview_rgb_img/README.md
- configs/body/2d_kpt_sview_rgb_img/README.md
- configs/body/3d_kpt_sview_rgb_img/README.md
- configs/face/2d_kpt_sview_rgb_img/README.md
- configs/hand/2d_kpt_sview_rgb_img/README.md
- configs/wholebody/2d_kpt_sview_rgb_img/README.md
> [Doc] Fix demo doc urls

- README.md
- README_CN.md
- docs/en/changelog.md
> Bump version to v0.24.0

- mmpose/datasets/builder.py
- tools/train.py
Refer to: https://github.com/open-mmlab/mmengine/pull/114/files
**Before PR**:
**After PR**:
> [Feature] support different torch seed for each rank

- docker/Dockerfile
Resolve #1232 
**Before PR**:
**After PR**:
> [Fix] fix unmatched MMCV version in DockerFile 

- README.md
A simple line duplication removed in readme. No functionality change.
X
X
X
**Before PR**:
**After PR**:
> Remove line duplication in readme

- docs/en/tasks/2d_animal_keypoint.md
fix #1224 
**Before PR**:
**After PR**:
> [Doc] fix VOC link

- docs/en/install.md
- docs/zh_cn/install.md
Update docs about installation on Windows and macOS.
**Before PR**:
**After PR**:
> [Doc] Update docs about installation on Windows/macOS 

- README.md
- README_CN.md
> [Doc] fix ap-10k link in readme

- docs/en/getting_started.md
- docs/zh_cn/getting_started.md
- tools/dist_test.sh
- tools/dist_train.sh
Refert to: https://github.com/open-mmlab/mmselfsup/pull/232/files
**Before PR**:
**After PR**:
> [Feature] support multi machine dist training

- tools/webcam/README.md
- tools/webcam/configs/eyes/README.md
- tools/webcam/docs/example_cn.md
- tools/webcam/docs/get_started_cn.md
> [Doc] Improve webcam api docs

- tools/dataset/preprocess_h36m.py
- tools/test.py
- tools/train.py
Use the hyphen '-' in all argument names in argparse.
**Before PR**:
**After PR**:
> [Fix] fix hyphen in argparse

- .github/workflows/build.yml
> [Fix] Fix github workflow CI

- README.md
- README_CN.md
> [Doc] add quick installation guide

- configs/_base_/datasets/rhd2d.py
- docs/en/tasks/2d_hand_keypoint.md
- mmpose/datasets/datasets/hand/rhd2d_dataset.py
Fix issue #1261.
Fix the `skeleton_info` of RHD dataset info under  `mmpose/configs/_base_/datasets/rhd2d.py` by these modifications:
1.`link=('wrist', 'thumb1') `->` link=('wrist', 'thumb4')`
2.`link=('wrist', 'forefinger1')` -> `link=('wrist', 'forefinger4')`
3.l`ink=('wrist', 'middle_finger1') `-> `link=('wrist', 'middle_finger4')`
4.`link=('wrist', 'ring_finger1') `-> `link=('wrist', 'ring_finger4')`
5.`link=('wrist', 'pinky_finger1')` -> `link=('wrist', 'pinky_finger4')`
These modifications are minor, which will not affect the trained models.
Further, fix the paper info of COCO-Wholebody-Hand dataset under `mmpose/docs/en/tasks/2d_hand_keypoint.md`
**Before PR**:
**After PR**:
> [Fix] Fix `keypoint_info` of RHD dataset 

- README.md
- README_CN.md
- docs/en/changelog.md
- mmpose/version.py
> Bump version to v0.25.0

- tools/test.py
- tools/train.py
> [Fix] fix compatibility of `--local_rank`

- README.md
Remove "font" tags from README.md which is not supported in the pypi home page.
**Before PR**:
**After PR**:
> [Fix] Update readme to fix pypi home page

- README_CN.md
> [Fix] fix links in README_CN.md

- requirements/runtime.txt
Update required xtcocotools version to v1.12, which fixed a bug reported in #1280 .
**Before PR**:
**After PR**:
> [Fix] Update required xtcocotools version to v1.12

- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_fp16_coco.md
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrnet_fp16_coco.yml
> Update hrnet_fp16 ckpt download url

- README_CN.md
- docs/zh_cn/getting_started.md
- docs/zh_cn/tutorials/6_customize_runtime.md
Improve the completeness of Chinese Documentation.
Translate `docs/en/tutorials/6_customize_runtime.md` to its Chinese version in  `docs/zh_cn/tutorials/6_customize_runtime.md`.
**Before PR**:
(I do not modify any code.)
**After PR**:
> [Doc] Translate tutorial 6_customize_runtime

- tools/dist_train.sh
- tools/test.py
- tools/train.py
Fix #1337
- Fix missing `MASTER_ADDR`
- Remove the setting of `--seed 0` to be consistent with `slurm_train.sh`
**Before PR**:
**After PR**:
> [Fix] Fix bugs distributed training

- mmpose/datasets/datasets/top_down/topdown_posetrack18_video_dataset.py
- tests/test_datasets/test_top_down_dataset.py
1. Remove the image file's existence check in `TopDownPoseTrack18VideoDataset`, to avoid incorrect dataset content when the image files do not present locally, e.g, using Ceph as backend to load the image file.
2. Modify related unittests.
**Before PR**:
**After PR**:
> [Fix] Remove image file's existence check in `TopDownPoseTrack18VideoDataset`

- .dev_scripts/benchmark/benchmark_cfg.yaml
- configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.md
- configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.yml
> [Enhance] Update benchmark regression list

- README.md
- README_CN.md
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvt-s_coco_256x192.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvt_coco.md
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvt_coco.yml
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvtv2-b2_coco_256x192.py
- docs/en/papers/backbones/pvt.md
- docs/en/papers/backbones/pvtv2.md
- mmpose/models/backbones/__init__.py
- mmpose/models/backbones/pvt.py
- mmpose/models/utils/__init__.py
- mmpose/models/utils/ckpt_convert.py
- mmpose/models/utils/transformer.py
- model-index.yml
- tests/test_backbones/test_pvt.py
> [Feature] add PVT backbone and configs

- .circleci/config.yml
- .circleci/test.yml
- .github/workflows/build.yml
- docker/Dockerfile
Refer to: https://github.com/open-mmlab/mmocr/pull/988
**Before PR**:
**After PR**:
> [Fix] Fix GPG key error in CI and docker

- mmpose/apis/inference.py
- mmpose/datasets/pipelines/shared_transform.py
Allow ToTensor to automaticly upload data to gpu, so that Normalize will be done in GPU.
Fix #1316
The inference for big image size is so slow. Because there are so many numpy array coping. And the data normalize should also be done in GPU if possible. After my revision, the cpu usage is significantly reduced, and the speed is increased.
**Before PR**:
**After PR**:
> [Enhance] Speed up the inference by reducing numpy array copy and doing Normalization in GPU

- README.md
- README_CN.md
- docs/en/changelog.md
- mmpose/__init__.py
- mmpose/version.py
> Bump version v0.26.0

- demo/body3d_two_stage_img_demo.py
fix #1372 
**Before PR**:
**After PR**:
> [Fix] fix a bug in demo

- README_CN.md
A link is broken.
Fixed the link.
**Before PR**:
**After PR**:
> Doc: Fix broken link to install.md

- mmpose/core/bbox/transforms.py
Fix bbox transform according to #1367 
**Before PR**:
**After PR**:
> [Fix] fix bbox transform

- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvt-s_coco_256x192.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/pvtv2-b2_coco_256x192.py
Update configs according to #1311 
**Before PR**:
**After PR**:
> [Fix] fix PVT configs

- docs/en/collect.py
- docs/en/papers/backbones/i3d.md
- docs/zh_cn/collect.py
Fix a bug in model zoo collection introduced by #1380 
**Before PR**:
**After PR**:
> [Fix] fix doc page of model-zoo

- README.md
- README_CN.md
- docs/en/changelog.md
- docs/en/index.rst
- docs/en/tutorials/7_webcam_api.md
- mmpose/version.py
> Bump version v0.27.0

- docs/en/tasks/2d_hand_keypoint.md
Fix freihand annotations link in #1420 
**Before PR**:
**After PR**:
> [Fix] Fix freihand annotations link

- demo/docs/2d_animal_demo.md
Add resource videos for animal demos.
**Before PR**:
**After PR**:
> [Doc] update animal demos

- demo/webcam_demo.py
- mmpose/apis/webcam/nodes/helper_nodes/recorder_node.py
- mmpose/apis/webcam/nodes/node.py
- mmpose/apis/webcam/utils/event.py
- mmpose/apis/webcam/webcam_executor.py
- Fix a deadlock issue that may block the exit of the webcam demo when using a video file as the input
- Improve the logging information
**Before PR**:
**After PR**:
> [Fix] fix deadlock in webcam demo

- configs/_base_/default_runtime.py
Default startup request from PAVI to provide support for internal services.
Optimization for PAVI startup.
> Pavi logger hook

- configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/tcformer_coco-wholebody.md
- configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/tcformer_coco-wholebody.yml
- configs/wholebody/2d_kpt_sview_rgb_img/topdown_heatmap/coco-wholebody/tcformer_coco_wholebody_256x192.py
- docs/en/papers/backbones/tcformer.md
- mmpose/models/backbones/__init__.py
- mmpose/models/backbones/tcformer.py
- mmpose/models/necks/__init__.py
- mmpose/models/necks/tcformer_mta_neck.py
- mmpose/models/utils/__init__.py
- mmpose/models/utils/ckpt_convert.py
- mmpose/models/utils/tcformer_utils.py
- model-index.yml
- tests/test_backbones/test_tcformer.py
- tests/test_necks/test_tcformer_mta_neck.py
> [Feature] add tcformer as a backbone

- mmpose/models/utils/tcformer_utils.py
> fix the bug in fp16 training of TCFormer

- demo/bottom_up_pose_tracking_demo.py
- demo/top_down_pose_tracking_demo_with_mmdet.py
> [Enhance] add progress bar in bottom-up tracking demo

- demo/body3d_two_stage_video_demo.py
Fix #1455 
**Before PR**:
**After PR**:
> [Fix] fix keypoint_key in smoother config in 3d video demo

- docs/en/tasks/2d_face_keypoint.md
Fix the COFW Dataset link in https://github.com/open-mmlab/mmpose/issues/1420
**Before PR**:
**After PR**:
> [Fix] Fix COFW Dataset link

- configs/body/3d_kpt_sview_rgb_img/pose_lift/mpi_inf_3dhp/simplebaseline3d_mpi-inf-3dhp.md
- docs/en/tasks/3d_body_mesh.md
> [Fix] Fix typo and format md files

- demo/docs/webcam_demo.md
- demo/webcam_demo.py
> [Enhance] support quick device setting in webcam demo

- README.md
- README_CN.md
- docs/en/changelog.md
- docs/en/papers/backbones/tcformer.md
- mmpose/version.py
> Bump version 0.28.0

- demo/MMPose_Tutorial.ipynb
> [Fix] fix down link in MMPose_Tutorial.ipynb

- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrformer_base_coco_384x288.py
- configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/hrformer_small_coco_384x288.py
Fix #1498 
**Before PR**:
**After PR**:
> [Fix] Remove unnecessary pipeline in val_pipeline

- configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_udp_rhd2d.md
- configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/rhd2d/hrnetv2_udp_rhd2d.yml
Fix typos in modelzoo.
**Before PR**:
**After PR**:
> [Fix] fix typo in markdown

- README_CN.md
- configs/_base_/filters/smoothnet_h36m.md
- demo/body3d_multiview_detect_and_regress_img_demo.py
- demo/body3d_two_stage_img_demo.py
- mmpose/models/backbones/resnet.py
- mmpose/models/backbones/vipnas_resnet.py
Fix some typos for to and the.
Fix Model Zoo link in README_CN.md.
Fix some typos for to and the.
Fix Model Zoo link in README_CN.md.
**Before PR**:
**After PR**:
> Fix some typos for Model Zoo, to and the.

- mmpose/core/utils/tensor_utils.py
- mmpose/datasets/pipelines/formatting.py
- mmpose/datasets/pipelines/topdown_transforms.py
- mmpose/models/heads/__init__.py
- mmpose/models/heads/base_head.py
- mmpose/models/heads/heatmap_heads/__init__.py
- mmpose/models/heads/heatmap_heads/heatmap_head.py
- mmpose/models/losses/__init__.py
- mmpose/models/losses/heatmap_loss.py
- mmpose/models/losses/mesh_loss.py
- mmpose/models/losses/mse_loss.py
- mmpose/testing/__init__.py
- mmpose/testing/_utils.py
- tests/test_datasets/test_pipelines/test_formatting.py
- tests/test_models/test_heads/test_heatmap_heads/test_headmap_head.py
Add unit test for `HeatmapHead`.
**Before PR**:
**After PR**:
> [Refactor] add unittest for `HeatmapHead`

- README.md
- README_CN.md
Unify the name of the environment according to docs/zh_cn/install.md and docs/en/install.md.
Unify the name of the environment according to docs/zh_cn/install.md and docs/en/install.md.
**Before PR**:
**After PR**:
> Unify the name of the environment.

- mmpose/__init__.py
- mmpose/models/heads/base_head.py
- mmpose/models/heads/heatmap_heads/heatmap_head.py
- mmpose/models/heads/regression_heads/regression_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_headmap_head.py
- Fix mmcv minimum/maximum version
- Fix bugs in unit tests
**Before PR**:
**After PR**:
> [Fix] fix mmcv version and unittests

- demo/docs/2d_hand_demo.md
- demo/docs/mmdet_modelzoo.md
Update links for pose model zoo.
Update links for pose model zoo.
**Before PR**:
**After PR**:
> [Doc] Update links for pose_model_zoo and log.

- .github/workflows/build.yml
- mmpose/core/keypoint/__init__.py
- mmpose/core/keypoint/codecs/__init__.py
- mmpose/core/keypoint/codecs/wrappers.py
- tests/test_core/test_keypoint/test_codecs/test_megvii_heatmap.py
- tests/test_core/test_keypoint/test_codecs/test_msra_heatmap.py
- tests/test_core/test_keypoint/test_codecs/test_udp_heatmap.py
- tests/test_core/test_keypoint/test_codecs/test_wrappers.py
- add `TestMultiLevelHeatmapEncoder` for multi-level heatmap encoding
**Before PR**:
**After PR**:
> [Feature] add encoder wrapper for multi-level heatmap encoding

- mmpose/apis/inference.py
- tests/test_datasets/test_transforms/test_topdown_transforms.py
> [Fix] Fix failed unittests

- configs/tests/hrnet_w32_coco_256x192.py
- mmpose/codecs/base.py
- mmpose/datasets/transforms/__init__.py
- mmpose/datasets/transforms/common_transforms.py
- mmpose/structures/bbox/legacy/transforms.py
- mmpose/structures/bbox/transforms.py
- tests/test_datasets/test_transforms/test_common_transforms.py
replace all  class name usage of `Bbox` with `BBox` 
**Before PR**:
**After PR**:
> [Refactor] replace Bbox with BBox

- mmpose/engine/__init__.py
- mmpose/engine/hooks/__init__.py
- mmpose/engine/hooks/visualization_hook.py
- mmpose/registry.py
- mmpose/visualization/local_visualizer.py
- tests/test_engine/test_hooks/test_visualization_hook.py
- tests/test_visualization/test_pose_visualizer.py
- Add PoseVisualizationHook
- Fix the bug about string color parameter in PoseVisualizer  
**Before PR**:
**After PR**:
> [Feature] Add pose visualizer hook

- configs/_base_/default_runtime.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_384x288.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_384x288_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_256x192_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_384x288_dark.py
- mmpose/evaluation/metrics/coco_metric.py
- mmpose/models/heads/heatmap_heads/heatmap_head.py
- mmpose/registry.py
Verify the model accuracy.
Add related configs of HRNet and HRNet + Dark model on COCO dataset. 
All added configs' mAP are aligned with previous version.
**Before PR**:
**After PR**:
> [Refactor] Verify HRNet & HRNet + Dark model test accuracy on COCO dataset

- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_384x288.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_384x288_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_256x192_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_384x288_dark.py
> [Fix]  Replace Bbox with BBox in configs 

- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192_udp.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_256x192_udp_regress.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_384x288.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_384x288_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w32_coco_384x288_udp.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_256x192_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_256x192_udp.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_384x288.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_384x288_dark.py
- configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_w48_coco_384x288_udp.py
- configs/tests/hrnet_w32_coco_256x192.py
- mmpose/codecs/udp_heatmap.py
- tests/test_codecs/test_udp_heatmap.py
> [Fix] fix an error in UDP decoding

- mmpose/core/evaluation/top_down_eval.py
> [Fix] Fix udp_combined decode bug

- mmpose/datasets/datasets/face/aflw_dataset.py
- mmpose/datasets/datasets/face/face_300w_dataset.py
- mmpose/datasets/datasets/face/wflw_dataset.py
- mmpose/evaluation/functional/keypoint_eval.py
- mmpose/evaluation/metrics/coco_metric.py
- mmpose/evaluation/metrics/keypoint_2d_metrics.py
- mmpose/models/backbones/mobilenet_v3.py
- mmpose/models/backbones/vipnas_mbv3.py
- mmpose/models/heads/base_head.py
- mmpose/models/heads/heatmap_heads/heatmap_head.py
1. manually set HSigmoid params
2. change the shape of `center`, `scale` to (1, 2) for (2,) in face datasets
3. manually convert `mask` to boolean array in `_calc_distances`
5. use `bbox_centers` and `bbox_scales` when `bboxes` is absent from `gt_instances` in `BaseHead.decode`
**Before PR**:
**After PR**:
> [Fix] fix bugs in testing process of topdown heatmap models

- mmpose/datasets/datasets/animal/locust_dataset.py
- mmpose/datasets/datasets/animal/zebra_dataset.py
- mmpose/datasets/datasets/base/base_coco_style_dataset.py
- mmpose/datasets/datasets/body/jhmdb_dataset.py
- mmpose/datasets/datasets/body/mpii_dataset.py
- mmpose/datasets/datasets/body/mpii_trb_dataset.py
- mmpose/datasets/datasets/body/posetrack18_video_dataset.py
- mmpose/datasets/datasets/face/aflw_dataset.py
- mmpose/datasets/datasets/face/coco_wholebody_face_dataset.py
- mmpose/datasets/datasets/face/face_300w_dataset.py
- mmpose/datasets/datasets/face/wflw_dataset.py
- mmpose/datasets/datasets/hand/coco_wholebody_hand_dataset.py
- mmpose/datasets/datasets/hand/freihand_dataset.py
- mmpose/datasets/datasets/hand/panoptic_hand2d_dataset.py
- mmpose/datasets/datasets/wholebody/coco_wholebody_dataset.py
- mmpose/datasets/transforms/common_transforms.py
- mmpose/datasets/transforms/formatting.py
- mmpose/datasets/transforms/topdown_transforms.py
- mmpose/evaluation/functional/keypoint_eval.py
- mmpose/evaluation/metrics/keypoint_2d_metrics.py
- tests/test_datasets/test_transforms/test_topdown_transforms.py
- tests/test_evaluation/test_metrics/test_keypoint_2d_metrics.py
Keep 'keypoints' unchanged in val_pipeline and test_pipelin. Otherwise, it will lead to incorrect evaluation results.
**Before PR**:
**After PR**:
> [Fix] Keep gt keypoints unchanged in val/test pipelines

- configs/body_2d_keypoint/topdown_regression/coco/res50_coco_256x192.py
- configs/body_2d_keypoint/topdown_regression/coco/res50_coco_256x192_rle.py
- configs/body_2d_keypoint/topdown_regression/mpii/res50_mpii_256x256.py
- configs/body_2d_keypoint/topdown_regression/mpii/res50_mpii_256x256_rle.py
- mmpose/codecs/regression_label.py
- mmpose/models/heads/heatmap_heads/cpm_head.py
- mmpose/models/heads/heatmap_heads/mspn_head.py
- mmpose/models/heads/heatmap_heads/simcc_head.py
- mmpose/models/heads/regression_heads/dsnt_head.py
- mmpose/models/heads/regression_heads/integral_regression_head.py
- mmpose/models/heads/regression_heads/regression_head.py
- mmpose/models/heads/regression_heads/rle_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_cpm_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_mspn_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_simcc_head.py
- tests/test_models/test_heads/test_regression_heads/test_dsnt_head.py
- tests/test_models/test_heads/test_regression_heads/test_integral_regression_head.py
- tests/test_models/test_heads/test_regression_heads/test_regression_head.py
- tests/test_models/test_heads/test_regression_heads/test_rle_head.py
> [Fix] Fix bugs in RLE training

- mmpose/datasets/transforms/formatting.py
- mmpose/engine/hooks/visualization_hook.py
- mmpose/structures/__init__.py
- mmpose/visualization/local_visualizer.py
- tests/test_datasets/test_transforms/test_formatting.py
- tools/misc/browse_dataset.py
> [Refactor] Fix bugs of browsing transformed training images

- mmpose/datasets/transforms/common_transforms.py
- tests/test_datasets/test_transforms/test_common_transforms.py
> [Refactor] fix halfbody transform

- mmpose/models/pose_estimators/topdown.py
> [Fix] fix lint

- mmpose/datasets/transforms/common_transforms.py
> [Fix] fix scale distribution in RandomBBoxTransform

- docs/en/dataset_zoo/2d_animal_keypoint.md
- docs/en/dataset_zoo/2d_face_keypoint.md
- docs/en/dataset_zoo/3d_body_keypoint.md
- docs/en/installation.md
- docs/en/user_guides/inference.md
- docs/en/user_guides/prepare_datasets.md
- docs/en/user_guides/train_and_test.md
- requirements/mminstall.txt
- requirements/optional.txt
1. Add `docs/en/user_guides/inference.md`
2. Add `docs/en/user_guides/prepare_datasets.md`
3. Add `docs/en/user_guides/train_and_test.md`
4. Modify some docs under `docs/en/dataset_zoo`
TODO:
1. Modify `docs/en/installation.md`
**Before PR**:
**After PR**:
> [Refactor] [Doc] Add `train_and_test.md`, `inference.md`, `prepare_datasets.md` and `installation.md`

- docs/en/notes/changelog.md
- docs/zh_cn/notes/changelog.md
> [Fix] Refine changelog

- mmpose/structures/utils.py
> [Fix] fix circular import

- configs/body/2d_kpt_sview_rgb_img/deeppose/mpii/res50_mpii_256x256_rle.py
> [Fix] Add bbox padding operation for res50_mpii_256x256_rle

- docs/en/api.rst
- docs/en/installation.md
- docs/zh_cn/api.rst
- docs/zh_cn/installation.md
> [Doc] fix section levels of installation guide

- docs/en/overview.md
- docs/zh_cn/overview.md
> [Doc] Review overview.md

- docs/en/notes/contribution_guide.md
- docs/en/notes/faq.md
- docs/en/user_guides/codecs.md
- docs/zh_cn/notes/contribution_guide.md
- docs/zh_cn/user_guides/codecs.md
- Update contribution guide: original contribution guide in 1.x is derived from v0.26.0. This PR updates the outdated part about the pre-commit configuration.
- Minor modifications to the codec introduction.
**Before PR**:
**After PR**:
> [Doc] review notes and codec documents

- docs/en/collect_modelzoo.py
- docs/zh_cn/collect_modelzoo.py
> [Fix] fix model zoo collection

- mmpose/codecs/associative_embedding.py
> [Fix] replace tensor.tile with tensor.repeat for PyTorch 1.6 compatibility

- mmpose/codecs/utils/refinement.py
- mmpose/models/utils/tta.py
1. Fix index of `refine_keypoints` in `mmpose/mmpose/codecs/utils/refinement.py`
2. Fix GPU and CPU device assignment op in `mmpose/mmpose/models/utils/tta.py`
**Before PR**:
**After PR**:
> [Fix] Fix `refine_keypoints` index bug and avoid wrong assignment  in CPU

- tools/analysis_tools/get_flops.py
Fix bug in `tools/analysis_tools/get_flops.py`. Use `_forward`  instead of `extract_feat` to include flops in head.
**Before PR**:
**After PR**:
> [Fix] use _forward for flops calculation

- mmpose/codecs/utils/refinement.py
> [Fix] Fix bug in dark decoding

- demo/webcam_cfg/pose_estimation.py
- mmpose/apis/webcam/utils/buffer.py
- mmpose/apis/webcam/utils/message.py
- mmpose/apis/webcam/utils/misc.py
- mmpose/apis/webcam/utils/pose.py
- mmpose/apis/webcam/webcam_executor.py
- mmpose/visualization/local_visualizer.py
- tests/test_apis/test_webcam/test_nodes/test_big_eye_effect_node.py
- tests/test_apis/test_webcam/test_nodes/test_detector_node.py
- tests/test_apis/test_webcam/test_nodes/test_monitor_node.py
- tests/test_apis/test_webcam/test_nodes/test_notice_board_node.py
- tests/test_apis/test_webcam/test_nodes/test_object_assigner_node.py
- tests/test_apis/test_webcam/test_nodes/test_object_visualizer_node.py
- tests/test_apis/test_webcam/test_nodes/test_pose_estimator_node.py
- tests/test_apis/test_webcam/test_nodes/test_recorder_node.py
- tests/test_apis/test_webcam/test_nodes/test_sunglasses_effect_node.py
- tests/test_apis/test_webcam/test_utils/test_buffer.py
- tests/test_apis/test_webcam/test_utils/test_event.py
- tests/test_apis/test_webcam/test_utils/test_image_capture.py
- tests/test_apis/test_webcam/test_utils/test_message.py
- tests/test_apis/test_webcam/test_utils/test_misc.py
- tests/test_apis/test_webcam/test_utils/test_pose.py
- tests/test_apis/test_webcam/test_webcam_executor.py
> [Refactor] Add Webcam API unittests

- demo/MMPose_Tutorial.ipynb
> [Fix] Fix colab tutorial link

- mmpose/datasets/datasets/base/base_coco_style_dataset.py
> [Fix] fix a bug in loading dataset metainfo from configs

- docker/Dockerfile
Fix #1703 
**Before PR**:
**After PR**:
> [Fix] Fix mmcv version in dockerfile

- README.md
- README_CN.md
- docs/en/notes/changelog.md
- mmpose/version.py
> Bump version v1.0.0rc0

- .circleci/test.yml
- .github/workflows/build.yml
- requirements.txt
- requirements/optional.txt
- requirements/poseval.txt
- setup.py
> [Fix] Fix pypi depoyment

- README.md
> [Fix] update README.md

- mmpose/apis/inference.py
The inference of DEKR models requires `'heatmap_size'` and `'skeleton'` in `img_metas`, which are not supported in the current inference function.
**Before PR**:
**After PR**:
> [Fix] Modify bottom-up inference function to support DEKR

- .owners.yml
> [Enhance] Add openmmlab-bot configuration for automatic issue assigning

- .owners.yml
> [Fix] Update .owners.yml

- README.md
- README_CN.md
add MMYOLO desc in README.md
add MMYOLO desc in README.md
**Before PR**:
**After PR**:
> add MMYOLO desc in README

- .owners.yml
> [Fix] update openmmlab-bot config

- demo/topdown_demo_with_mmdet.py
- demo/topdown_face_demo.py
- mmpose/apis/inference.py
- mmpose/structures/utils.py
> [Fix] support empty detection result in top-down demo

- configs/face_2d_keypoint/topdown_heatmap/300w/td-hm_hrnetv2-w18_8xb64-60e_300w-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/aflw/td-hm_hrnetv2-w18_8xb64-60e_aflw-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/aflw/td-hm_hrnetv2-w18_dark-8xb64-60e_aflw-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/coco_wholebody_face/td-hm_hourglass52_8xb32-60e_coco-wholebody-face-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/coco_wholebody_face/td-hm_hrnetv2-w18_8xb32-60e_coco-wholebody-face-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/coco_wholebody_face/td-hm_hrnetv2-w18_dark-8xb32-60e_coco-wholebody-face-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/coco_wholebody_face/td-hm_mobilenetv2_8xb32-60e_coco-wholebody-face-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/coco_wholebody_face/td-hm_res50_8xb32-60e_coco-wholebody-face-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/coco_wholebody_face/td-hm_scnet50_8xb32-60e_coco-wholebody-face-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/cofw/td-hm_hrnetv2-w18_8xb64-60e_cofw-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/wflw/td-hm_hrnetv2-w18_8xb64-60e_wflw-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/wflw/td-hm_hrnetv2-w18_awing-8xb64-60e_wflw-256x256.py
- configs/face_2d_keypoint/topdown_heatmap/wflw/td-hm_hrnetv2-w18_dark-8xb64-60e_wflw-256x256.py
> [Fix] fix save-best rule for NME

- tests/test_datasets/test_transforms/test_loading.py
> [Improve] add unittest for loading

- configs/body_2d_keypoint/simcc/coco/mobilenetv2_coco.yml
- configs/body_2d_keypoint/simcc/coco/resnet_coco.yml
- configs/body_2d_keypoint/simcc/coco/vipnas_coco.yml
- configs/body_2d_keypoint/topdown_heatmap/coco/hourglass_coco.yml
- model-index.yml
Add metafiles for hourglass and simcc models
**Before PR**:
**After PR**:
> [Enhance] Add metafiles for hourglass and simcc models

- mmpose/__init__.py
> [Improve] update maximum mmcv version to 1.8.0

- tools/dataset/preprocess_h36m.py
Refer to #1751 
**Before PR**:
**After PR**:
> [Fix] patch CVE-2007-4559

- mmpose/registry.py
Add full registry definitions in MMPose (even those with no mmpose module registered) to avoid disturbing warning information (as reported in #1699 and #1819)
- `mmpose/registry.py`
**Before PR**:
**After PR**:
> [Fix] Add full registries to avoid warning

- docs/en/dataset_zoo/2d_animal_keypoint.md
> [Fix] Update MacaquePose dataset link

- configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_hrnet-w32_8xb64-210e_ap10k-256x256.py
- configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_hrnet-w48_8xb64-210e_ap10k-256x256.py
- configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_res101_8xb64-210e_ap10k-256x256.py
- configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_res50_8xb64-210e_ap10k-256x256.py
- mmpose/datasets/datasets/animal/ap10k_dataset.py
- mmpose/datasets/datasets/base/base_coco_style_dataset.py
- mmpose/datasets/transforms/formatting.py
- mmpose/evaluation/metrics/__init__.py
- mmpose/evaluation/metrics/coco_metric.py
- tests/test_evaluation/test_metrics/test_coco_metric.py
Fix some bug in AP10kCocoMetric. Related issue: https://github.com/open-mmlab/mmpose/issues/1726
The test accuracy is verified on these four configs: https://github.com/open-mmlab/mmpose/tree/dev-1.x/configs/animal_2d_keypoint/topdown_heatmap/ap10k
1. Merge the `Ap10kCocoMetric` into `CocoMetric`
2. Modify the related configs
3. Modify the dataset and `formatting.py`
4. Fix unittests.
**Before PR**:
**After PR**:
> [Fix] Fix AP10k metric

- mmpose/datasets/pipelines/top_down_transform.py
Without this conversion the subtraction in calling get_warp_matrix will not work for tuples.
`image_size` converted to np.ndarray.
For models that call use_udp and have non rectangular inputs.
**Before PR**:
**After PR**:
> [Fix] Conversion of image_size to ndarray

- mmpose/codecs/simcc_label.py
- mmpose/codecs/utils/__init__.py
- mmpose/codecs/utils/post_processing.py
- mmpose/codecs/utils/refinement.py
- tests/test_codecs/test_simcc_label.py
> [Feature] Add DARK to SimCC

- docs/en/tasks/2d_hand_keypoint.md
- docs/en/tasks/3d_hand_keypoint.md
> [Doc] update interhand2.6m annotation link

- demo/bottomup_demo.py
- demo/docs/2d_human_pose_demo.md
- demo/topdown_demo_with_mmdet.py
- demo/topdown_face_demo.py
Some users need to know the meaning of each keypoint output by demos for downstream tasks. https://github.com/open-mmlab/mmpose/issues/1851 is an example
1. saving dataset_meta in demo outputs
2. support video inputs for bottom-up demo
3. add doc for bottom-up demo
**Before PR**:
**After PR**:
> [Feature] Saving metainfo in demo outputs

- configs/hand_2d_keypoint/topdown_heatmap/coco_wholebody_hand/td-hm_mobilenetv2_8xb32-210e_coco-wholebody-hand-256x256.py
mobilenetv2's out_channel is 1280 not 2048.
Fix #1905 
**Before PR**:
**After PR**:
> [Fix] Update td-hm_mobilenetv2_8xb32-210e_coco-wholebody-hand-256x256.py

- configs/body/2d_kpt_sview_rgb_img/deeppose/coco/resnet_rle_coco.yml
- configs/body/2d_kpt_sview_rgb_img/deeppose/mpii/resnet_rle_mpii.yml
- docs/en/papers/techniques/rle.md
Add rle.md in papers/techniques/
**Before PR**:
**After PR**:
> [Docs] Fix link in the modelzoo

- .owners.yml
> [Improve] update .owners.yml

- .pre-commit-config.yaml
- docs/en/migration.md
- docs/en/user_guides/train_and_test.md
- docs/en/user_guides/visualization.md
- docs/zh_cn/migration.md
The methods to specify dataset metainfo files are different in MMPose 0.x/1.x, which might be confusing when users want to train models on their own datasets (e.g. https://github.com/open-mmlab/mmpose/issues/1941). 
**Before PR**:
**After PR**:
> [Doc] Add instruction for assigning dataset metainfo file in migration

- configs/_base_/default_runtime.py
- mmpose/codecs/associative_embedding.py
- mmpose/models/heads/heatmap_heads/cpm_head.py
- mmpose/models/heads/heatmap_heads/heatmap_head.py
- mmpose/models/heads/heatmap_heads/vipnas_head.py
- mmpose/models/losses/heatmap_loss.py
- mmpose/structures/keypoint/transforms.py
- tests/test_models/test_heads/test_heatmap_heads/test_cpm_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_heatmap_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_simcc_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_vipnas_head.py
- tests/test_models/test_losses/test_heatmap_losses.py
The implementation of `AdaptiveWingLoss` is using `keypoint_weights` in an incorrect manner. (see https://github.com/open-mmlab/mmpose/issues/1947)
1. fix bug in `AdaptiveWingLoss`
2. add unittest for `AdaptiveWingLoss`
**Before PR**:
**After PR**:
> [Fix] fix AdaptiveWingLoss

- mmpose/datasets/__init__.py
- mmpose/datasets/samplers.py
Sampling data from CombinedDataset with specified source ratio
**Before PR**:
**After PR**:
> [Feature] add multi-source sampler

- demo/image_demo.py
- docs/en/installation.md
Add the argument `show` with a default value of `False` to `demo/image_demo.py` to avoid getting stuck on platforms without GUI
**Before PR**:
**After PR**:
> [Fix] fix image_demo.py used for installation verification

- mmpose/datasets/transforms/formatting.py
> [Enhance] faster image transpose using tensor instead of numpy array

- mmpose/datasets/datasets/body3d/body3d_mview_direct_panoptic_dataset.py
- mmpose/datasets/pipelines/bottom_up_transform.py
- tests/test_models/test_bottom_up_forward.py
numpy 1.24.0 removes np.bool, np.float, np.int. 
To fix it, I replace np.int (and some np.int64) with np.int32.
**Before PR**:
**After PR**:
> [Fix] replace np.int with int

- demo/topdown_demo_with_mmdet.py
- mmpose/structures/utils.py
> [Fix] fix topdown demo bug when no obj detected

- projects/README.md
- projects/example_project/README.md
- projects/faq.md
1. add FAQ for projects
2. refine `projects/example_project/README.md` to add more explicit guidance
**Before PR**:
**After PR**:
> [Enhance] refine example_project README

- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
- projects/rtmpose/rtmpose/pruning/README.md
- projects/rtmpose/rtmpose/pruning/README_CN.md
- projects/rtmpose/rtmpose/pruning/group_fisher_deploy_rtmpose-s_8xb256-420e_aic-coco-256x192.py
- projects/rtmpose/rtmpose/pruning/group_fisher_deploy_rtmpose-s_8xb256-420e_coco-256x192.py
- projects/rtmpose/rtmpose/pruning/group_fisher_finetune_rtmpose-s_8xb256-420e_aic-coco-256x192.py
- projects/rtmpose/rtmpose/pruning/group_fisher_finetune_rtmpose-s_8xb256-420e_coco-256x192.py
- projects/rtmpose/rtmpose/pruning/group_fisher_prune_rtmpose-s_8xb256-420e_aic-coco-256x192.py
- projects/rtmpose/rtmpose/pruning/group_fisher_prune_rtmpose-s_8xb256-420e_coco-256x192.py
- tools/train.py
> [Feature] add rtmpose pruned version

- configs/body_2d_keypoint/topdown_heatmap/coco/vitpose_coco.md
- docker/serve/Dockerfile
- docs/en/installation.md
- docs/en/notes/changelog.md
- docs/en/notes/faq.md
- docs/src/papers/algorithms/cid.md
- docs/src/papers/algorithms/dekr.md
- docs/src/papers/algorithms/vitpose.md
- docs/zh_cn/installation.md
- docs/zh_cn/notes/faq.md
- mmpose/__init__.py
- mmpose/apis/inferencers/pose2d_inferencer.py
- mmpose/version.py
> Bump version to v1.0.0rc1

- .circleci/test.yml
> [Fix] fix circleci docker

- .circleci/docker/Dockerfile
> [Fix] update circle ci docker

- .readthedocs.yml
- docs/en/api.rst
- docs/en/merge_docs.sh
- docs/zh_cn/api.rst
- docs/zh_cn/merge_docs.sh
- Only compile epub format online documentation
- Fix outdated documentation index and scripts
**Before PR**:
**After PR**:
> [Fix] fix online docs

- README.md
- README_CN.md
- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Docs] update dev-1.x readme

- README.md
- README_CN.md
- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Docs] Update 1.x readme

- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Docs] update win tutorial in dev-1.x

- .github/workflows/build.yml
- mmpose/datasets/datasets/base/kpt_3d_mview_rgb_img_direct_dataset.py
> [Fix] fix CI

- projects/mmpose4aigc/openpose_visualization.py
> [Refine] refine skeleton visualization

- docs/en/dataset_zoo/2d_animal_keypoint.md
- docs/en/dataset_zoo/2d_body_keypoint.md
- docs/en/dataset_zoo/2d_face_keypoint.md
- docs/en/dataset_zoo/2d_fashion_landmark.md
- docs/en/dataset_zoo/2d_hand_keypoint.md
- docs/en/dataset_zoo/2d_wholebody_keypoint.md
- docs/en/dataset_zoo/3d_body_keypoint.md
- docs/en/dataset_zoo/3d_hand_keypoint.md
Added description of keypoints for datasets supported by mmpose.
Add visualization of keypoints order for datasets supported by mmpose, including 2D/3D hands, 2D/3D human bodies, fullbody, animal, etc.
Currently only the English document is updated, if the images meets the requirements, I will update it to the Chinese document synchronously.
**Before PR**:
**After PR**:
> [Docs] Add keypoints order images in doc

- docs/zh_cn/dataset_zoo/2d_animal_keypoint.md
- docs/zh_cn/dataset_zoo/2d_body_keypoint.md
- docs/zh_cn/dataset_zoo/2d_face_keypoint.md
- docs/zh_cn/dataset_zoo/2d_fashion_landmark.md
- docs/zh_cn/dataset_zoo/2d_hand_keypoint.md
- docs/zh_cn/dataset_zoo/2d_wholebody_keypoint.md
- docs/zh_cn/dataset_zoo/3d_body_keypoint.md
- docs/zh_cn/dataset_zoo/3d_hand_keypoint.md
Added description of keypoints for datasets supported by mmpose.
Add visualization of keypoints order for datasets supported by mmpose, including 2D/3D hands, 2D/3D human bodies, fullbody, animal, etc.
Update keypoints order to the Chinese document.
**Before PR**:
**After PR**:
> [Docs] Add keypoints order images in zh_cn doc

- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small_8xb64-210e_coco-256x192.py
Modify paths to the pretrained models
**Before PR**:
**After PR**:
> [Fix] Change ViTPose pretrained models' paths

- README.md
- README_CN.md
> [Doc] Add more social networking links(dev-1.x)

- mmpose/visualization/local_visualizer.py
fix the bug where the visualizer only draws a single instance
**Before PR**:
**After PR**:
> [Fix] fix PoseLocalVisualizer

- README.md
- README_CN.md
> [Docs] fix typo

- README.md
- README_CN.md
> [Docs] fold summaries

- mmpose/datasets/transforms/formatting.py
> [Fix] fix data transform

- README.md
- README_CN.md
- docs/en/get_started.md
- docs/en/language.md
- docs/en/tutorials/1_finetune.md
- docs/zh_cn/tutorials/1_finetune.md
> [Doc] update readme and doc links

- README.md
- README_CN.md
- mmpose/apis/inference.py
- mmpose/models/utils/check_and_update_config.py
> [Fix] Fix link in config checker

- mmpose/version.py
> Bump version to v1.0.0 (#2169)

- README.md
> add migration progress

- README.md
> add migration progress (#2177)

- mmpose/apis/train.py
- mmpose/core/distributed_wrapper.py
- mmpose/core/utils/dist_utils.py
- mmpose/utils/util_distribution.py
- tools/train.py
Added NPU(ascending device) support in mmpose
The main modification points are:
1. add NPUDataParallel、NPUDistributedDataParallel
**Before PR**:
**After PR**:
> [NPU] add Ascend NPU device support for mmpose

- .pre-commit-config.yaml
> [Fix] fix mmcv version

- projects/awesome-mmpose/README.md
- projects/rtmpose/README.md
> [Projects] Update AwesomeMMPose list

- .owners.yml
Add `.owners.yml` to enable automatic issue assigning.
**Before PR**:
**After PR**:
> [Improve] add .owners.yml

- mmpose/apis/train.py
Fix npu accuracy issues caused by not using fp16 in mmpose
**Before PR**:
**After PR**:
> [Improve]Fix NPU backend fp16 bug

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-feature_request.yml
- .github/ISSUE_TEMPLATE/3-general_questions.yml
> [Fix] Fix issue template

- .github/ISSUE_TEMPLATE/1-bug-report.yml
- .github/ISSUE_TEMPLATE/2-feature_request.yml
- .github/ISSUE_TEMPLATE/3-general_questions.yml
> [Fix] Update issue template

- docs/en/device/npu.md
- docs/zh_cn/device/npu_zh.md
- model-index.yml
Add NPU result.
Add docs/en/device/npu.md, add docs/zh_CN/device/npu.md.
None.
None.
**Before PR**:
**After PR**:
> [Docs] Add NPU support page

- README.md
- README_CN.md
Update repo information and URLs in README.
**Before PR**:
**After PR**:
> [Doc] update repo list in README

- mmpose/datasets/datasets/base/base_mocap_dataset.py
- mmpose/evaluation/functional/__init__.py
- mmpose/evaluation/functional/keypoint_eval.py
- mmpose/evaluation/functional/mesh_eval.py
- mmpose/evaluation/metrics/__init__.py
- mmpose/evaluation/metrics/keypoint_3d_metrics.py
- tests/test_evaluation/test_functional/test_keypoint_eval.py
- tests/test_evaluation/test_metrics/test_keypoint_3d_metrics.py
> [Refactor] add mpjpe metric

- mmpose/models/losses/classification_loss.py
- projects/rtmpose/examples/README.md
- projects/rtmpose/examples/RTMPose-Deploy/README.md
> [Enhance] Refine docs and code

- requirements/docs.txt
> [CI] fix docs ci

- configs/body_2d_keypoint/rtmpose/body8/rtmpose-l_8xb256-210e_body8-256x192.py
- configs/body_2d_keypoint/rtmpose/body8/rtmpose-l_8xb256-210e_body8-384x288.py
- configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb256-210e_body8-256x192.py
- configs/body_2d_keypoint/rtmpose/body8/rtmpose-m_8xb256-210e_body8-384x288.py
- configs/body_2d_keypoint/rtmpose/body8/rtmpose-s_8xb256-210e_body8-256x192.py
- configs/body_2d_keypoint/rtmpose/body8/rtmpose-t_8xb256-210e_body8-256x192.py
- configs/body_2d_keypoint/rtmpose/body8/rtmpose_body8.md
- configs/body_2d_keypoint/rtmpose/body8/rtmpose_body8.yml
- configs/face_2d_keypoint/rtmpose/lapa/rtmpose-m_8xb64-120e_lapa-256x256.py
- docs/en/dataset_zoo/2d_face_keypoint.md
- projects/rtmpose/README.md
- projects/rtmpose/examples/README.md
- projects/rtmpose/rtmpose/face_2d_keypoint/rtmpose-m_8xb64-120e_lapa-256x256.py
- tools/dataset_converters/lapa2coco.py
> [Enhance] Upload Body8 configs

- demo/topdown_demo_with_mmdet.py
> [Fix] fix topdown demo

- projects/yolox-pose/README.md
> [Doc] add mmyolo yolo-pose results

- mmpose/apis/inferencers/base_mmpose_inferencer.py
- projects/yolox-pose/configs/_base_/default_runtime.py
- projects/yolox-pose/configs/yolox-pose_s_8xb32-300e_coco.py
https://github.com/open-mmlab/mmpose/issues/2376
**Before PR**:
**After PR**:
> [Fix] fix YOLOX-Pose Inferencer with webcam input

- mmpose/models/utils/rtmcc_block.py
> [Fix] Fix ncnn bugs caused by negative axis

- projects/README.md
- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Docs] Update RTMPose Logo

- mmpose/apis/inferencers/base_mmpose_inferencer.py
> [Enhance] Support specifying output filename for inferencer

- README.md
- README_CN.md
- docs/en/notes/pytorch_2.md
- docs/zh_cn/notes/pytorch_2.md
> [Docs] Add PyTorch 2.0 Docs and update refactory progress

- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Docs] Update GIF for 26-kpt models

- configs/body_2d_keypoint/associative_embedding/coco/ae_hrnet-w32_8xb24-300e_coco-512x512.py
- demo/bottomup_demo.py
- mmpose/codecs/associative_embedding.py
- mmpose/datasets/transforms/bottomup_transforms.py
- mmpose/models/heads/heatmap_heads/ae_head.py
> Merge ae-test to ae-train

- configs/body_3d_keypoint/video_pose_lift/h36m/videopose3d_h36m.yml
- demo/body3d_pose_lifter_demo.py
- demo/docs/en/3d_human_pose_demo.md
- demo/inferencer_demo.py
- docs/en/user_guides/inference.md
- mmpose/apis/__init__.py
- mmpose/apis/inference_3d.py
- mmpose/apis/inferencers/__init__.py
- mmpose/apis/inferencers/base_mmpose_inferencer.py
- mmpose/apis/inferencers/mmpose_inferencer.py
- mmpose/apis/inferencers/pose2d_inferencer.py
- mmpose/apis/inferencers/pose3d_inferencer.py
- model-index.yml
- tests/test_apis/test_inferencers/test_mmpose_inferencer.py
- tests/test_apis/test_inferencers/test_pose3d_inferencer.py
> [Enhance] Add 3d pose inferencer

- docs/zh_cn/dataset_zoo/2d_face_keypoint.md
- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Docs] Add skeleton imgs to illustrate

- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Fix] Fix markdown format

- docs/en/user_guides/inference.md
- docs/zh_cn/user_guides/inference.md
- mmpose/apis/inferencers/base_mmpose_inferencer.py
- mmpose/apis/inferencers/pose3d_inferencer.py
- tests/test_apis/test_inferencers/test_pose3d_inferencer.py
> [Enhance] Pose3d inferencer supports image inputs

- demo/body3d_pose_lifter_demo.py
- demo/docs/en/3d_human_pose_demo.md
- mmpose/apis/inferencers/pose3d_inferencer.py
- mmpose/visualization/local_visualizer_3d.py
1. Add 3d human pose demo for image
2. Refactor `Pose3dLocalVisualizer` and modify corresponding inferencer
**Before PR**:
**After PR**:
> [Enhance] Add 3d human pose demo for image

- mmpose/models/losses/heatmap_loss.py
- tests/test_models/test_losses/test_heatmap_losses.py
https://github.com/open-mmlab/mmpose/issues/2464
**Before PR**:
**After PR**:
> [Fix] fix the mask calculation in KeypointMSELoss 

- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/vitpose_coco.md
- configs/body_2d_keypoint/topdown_heatmap/humanart/td-hm_ViTPose-base_8xb64-210e_humanart-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/humanart/td-hm_ViTPose-small_8xb64-210e_humanart-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/humanart/vitpose_humanart.md
> [Fix] update ViTPose dependency to mmpretrain

- mmpose/evaluation/metrics/keypoint_2d_metrics.py
> [Fix] Update NME default indices

- docs/zh_cn/user_guides/train_and_test.md
- docs/zh_cn/user_guides/useful_tools.md
- docs/zh_cn/user_guides/visualization.md
> [Docs] Update Docs

- setup.py
https://github.com/open-mmlab/mmpose/issues/2504, https://github.com/open-mmlab/mmpose/issues/1939
Due to an incompatibility between the Colab platform and the pre-built xtcocotools PyPI package, it is necessary to compile xtcocotools from source on Colab
**Before PR**:
**After PR**:
> [Fix] Fix numpy bug on Colab 

- mmpose/configs/body_2d_keypoint/rtmpose/coco/rtmpose_m_8xb256-420e_coco-256x192.py
- mmpose/configs/body_2d_keypoint/rtmpose/coco/rtmpose_s_8xb256_420e_aic_coco_256x192.py
- mmpose/configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w48_udp-8xb32-210e_coco-256x192.py
- projects/yolox_pose/configs/py_yolox_pose_s_8xb32_300e_coco.py
> [Fix] Fix new config with read_base

- docs/en/advanced_guides/codecs.md
- docs/en/advanced_guides/implement_new_models.md
- docs/en/guide_to_framework.md
- docs/zh_cn/advanced_guides/codecs.md
- docs/zh_cn/advanced_guides/implement_new_models.md
- docs/zh_cn/guide_to_framework.md
> [Doc] Update img in docs

- demo/body3d_pose_lifter_demo.py
- demo/bottomup_demo.py
- demo/topdown_demo_with_mmdet.py
- projects/just_dance/README.md
> [Fix] fix opencv waitkey bug in demo scripts 

- demo/body3d_pose_lifter_demo.py
- demo/bottomup_demo.py
- demo/image_demo.py
- demo/topdown_demo_with_mmdet.py
- mmpose/apis/inferencers/base_mmpose_inferencer.py
- mmpose/apis/inferencers/pose3d_inferencer.py
> [Enhance] Add notifications when saving visualization results in demos

- docs/en/installation.md
- docs/en/user_guides/configs.md
- docs/en/user_guides/train_and_test.md
- docs/zh_cn/installation.md
- docs/zh_cn/user_guides/configs.md
- docs/zh_cn/user_guides/train_and_test.md
> [Docs] Enhance documents

- docs/en/advanced_guides/customize_datasets.md
- docs/en/guide_to_framework.md
- docs/en/user_guides/configs.md
- docs/zh_cn/advanced_guides/customize_datasets.md
- docs/zh_cn/guide_to_framework.md
- docs/zh_cn/overview.md
- docs/zh_cn/user_guides/configs.md
> [Docs] Add more details to docs

- docs/en/user_guides/mixed_datasets.md
- docs/zh_cn/user_guides/mixed_datasets.md
- mmpose/datasets/dataset_wrappers.py
- tests/test_datasets/test_datasets/test_dataset_wrappers/test_combined_dataset.py
> [Enhance] Combined dataset supports custom sampling ratio

- docs/en/user_guides/mixed_datasets.md
- docs/zh_cn/user_guides/mixed_datasets.md
> [Docs] Add MultiSourceSampler docs

- docs/en/advanced_guides/customize_datasets.md
- docs/en/guide_to_framework.md
- docs/zh_cn/guide_to_framework.md
> [Doc] Refine docs

- tools/train.py
> [Fix] Fix new config bug in train.py

- demo/body3d_pose_lifter_demo.py
- demo/docs/en/3d_human_pose_demo.md
- demo/inferencer_demo.py
- docs/en/user_guides/inference.md
- docs/zh_cn/user_guides/inference.md
- mmpose/apis/inferencers/mmpose_inferencer.py
- mmpose/apis/inferencers/pose3d_inferencer.py
> [Enhance] Normalization option in 3d human pose demo and inferencer

- README.md
- README_CN.md
- demo/body3d_pose_lifter_demo.py
- docs/en/advanced_guides/implement_new_models.md
- docs/en/guide_to_framework.md
- docs/src/papers/algorithms/motionbert.md
- docs/zh_cn/advanced_guides/implement_new_models.md
- docs/zh_cn/guide_to_framework.md
- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Enhance] Enhance 3dpose demo and docs

- docs/en/advanced_guides/codecs.md
- docs/zh_cn/advanced_guides/codecs.md
- docs/zh_cn/guide_to_framework.md
> [Docs] Enhance Codecs documents

- mmpose/codecs/image_pose_lifting.py
- mmpose/codecs/motionbert_label.py
- mmpose/codecs/video_pose_lifting.py
- mmpose/datasets/datasets/base/base_mocap_dataset.py
- mmpose/datasets/datasets/body3d/h36m_dataset.py
> [Fix] Refine 3dpose

- projects/rtmpose/rtmpose/body_2d_keypoint/rtmpose-x_8xb256-700e_coco-384x288.py
> [Fix] Fix config typo in rtmpose-x

- mmpose/apis/inferencers/pose3d_inferencer.py
> [Fix] Fix 3d inferencer

- docs/en/user_guides/inference.md
- docs/zh_cn/user_guides/inference.md
- mmpose/apis/__init__.py
- mmpose/apis/visualization.py
> [Feature] Add a simple visualize api

- configs/body/2d_kpt_sview_rgb_img/cid/coco/res50_fpn_coco.md
- configs/body/2d_kpt_sview_rgb_img/cid/coco/res50_fpn_coco.yml
- configs/body/2d_kpt_sview_rgb_img/cid/coco/res50_fpn_coco_512x512.py
- model-index.yml
I try to train a CID whose backbone is resnet-50 and upload the model and config to mmpose server. 
The motivation is to compare CID with different works with res50 fairly.
add CID_res50_fpn config, md and yml
update model-index.yml
**Before PR**:
**After PR**:
> [feature] add CID-res50 config and model

- configs/_base_/datasets/coco_wholebody_openpose.py
- mmpose/visualization/local_visualizer.py
> [Enhance] wholebody support  openpose style visualization

- mmpose/engine/hooks/badcase_hook.py
> [Fix] fix badcase hook

- README.md
- README_CN.md
- docs/en/installation.md
- docs/en/user_guides/dataset_tools.md
- docs/zh_cn/dataset_zoo/2d_fashion_landmark.md
- docs/zh_cn/installation.md
- docs/zh_cn/overview.md
- docs/zh_cn/user_guides/dataset_tools.md
> [Docs] Refine Docs

- mmpose/datasets/transforms/common_transforms.py
> [Fix] Fix multiply to avoid numpy error

- docs/en/advanced_guides/customize_evaluation.md
- docs/en/index.rst
- docs/zh_cn/advanced_guides/customize_evaluation.md
- docs/zh_cn/index.rst
- mmpose/datasets/datasets/base/base_coco_style_dataset.py
- mmpose/datasets/datasets/base/base_mocap_dataset.py
- mmpose/datasets/datasets/body/mpii_dataset.py
- mmpose/datasets/datasets/body/mpii_trb_dataset.py
- mmpose/datasets/datasets/body/posetrack18_video_dataset.py
- mmpose/datasets/datasets/hand/coco_wholebody_hand_dataset.py
- tests/test_datasets/test_datasets/test_body_datasets/test_h36m_dataset.py
> [Fix] update error info and docs

- mmpose/visualization/local_visualizer.py
https://github.com/open-mmlab/mmpose/issues/2629
**Before PR**:
**After PR**:
> [Fix] fix a bug when visualize keypoint indices

- docs/en/user_guides/configs.md
- docs/zh_cn/user_guides/configs.md
> [Docs] Fix mmengine link

- README_CN.md
> Update QR code

- docs/en/user_guides/train_and_test.md
- docs/zh_cn/user_guides/train_and_test.md
- mmpose/datasets/datasets/base/base_coco_style_dataset.py
- mmpose/datasets/transforms/converting.py
- mmpose/datasets/transforms/formatting.py
- mmpose/evaluation/__init__.py
- mmpose/evaluation/evaluators/__init__.py
- mmpose/evaluation/evaluators/mutli_dataset_evaluator.py
- mmpose/evaluation/metrics/coco_metric.py
- mmpose/registry.py
- tests/test_datasets/test_transforms/test_converting.py
- tests/test_evaluation/test_evaluator/test_multi_dataset_evaluator.py
- tests/test_evaluation/test_metrics/test_coco_metric.py
example:
```python
aic_to_coco_converter = dict(
type='KeypointConverter',
num_keypoints=17,
mapping=[
(0, 6),
(1, 8),
(2, 10),
(3, 5),
(4, 7),
(5, 9),
(6, 12),
(7, 14),
(8, 16),
(9, 11),
(10, 13),
(11, 15),
])
dataset_coco_val = dict(
type=dataset_type,
data_root=data_root,
data_mode=data_mode,
ann_file='annotations/person_keypoints_val2017.json',
bbox_file='data/coco/person_detection_results/'
'COCO_val2017_detections_AP_H_56_person.json',
data_prefix=dict(img='val2017/'),    
test_mode=True,
pipeline=[],
)
dataset_aic_val = dict(
type='AicDataset',
data_root='data/aic/',
data_mode=data_mode,
ann_file='annotations/aic_val.json',
data_prefix=dict(img='ai_challenger_keypoint_validation_20170911/'
'keypoint_validation_images_20170911/'),
test_mode=True,
pipeline=[],
)
val_dataset = dict( …
```
> [Feature] Support multi-dataset evaluation

- mmpose/codecs/decoupled_heatmap.py
- mmpose/codecs/integral_regression_label.py
- mmpose/codecs/megvii_heatmap.py
- mmpose/codecs/msra_heatmap.py
- mmpose/codecs/regression_label.py
- mmpose/codecs/simcc_label.py
- mmpose/codecs/spr.py
- mmpose/codecs/udp_heatmap.py
- mmpose/datasets/transforms/pose3d_transforms.py
- mmpose/datasets/transforms/topdown_transforms.py
- mmpose/models/pose_estimators/topdown.py
- mmpose/testing/_utils.py
> [Refactor] update mapping tables

- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small-simple_8xb64-210e_coco-256x192.py
- configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small_8xb64-210e_coco-256x192.py
> [Fix] fix vitpose pretrained ckpts

- mmpose/evaluation/metrics/coco_metric.py
> [Fix] Fix a typo in CocoMetric

- README.md
- README_CN.md
Add OpenXLab Badge to share official applications, community applications and ecological applications based on MMPose in the OpenXLab platform.
Added OpenXLab Badge in ReadME（English & Chinese）
**Before PR**:
**After PR**:
> [Docs] Add OpenXLab Badge

- mmpose/apis/inferencers/base_mmpose_inferencer.py
- mmpose/apis/inferencers/mmpose_inferencer.py
- mmpose/apis/inferencers/pose2d_inferencer.py
- mmpose/apis/inferencers/pose3d_inferencer.py
mmdet and mmpose will update the inferencer argument `return_datasample` to `return_datasamples` in the new version. This may lead to errors if users use mismatched versions. 
**Before PR**:
**After PR**:
> [Fix] add compatibility for argument `return_datasample`

- mmpose/datasets/transforms/loading.py
> [Fix] Give more clues when loading img failed

- configs/body_2d_keypoint/yoloxpose/coco/yoloxpose_coco.md
- mmpose/codecs/annotation_processors.py
> [Fix] Fix the typo in YOLOX-Pose

- README.md
- README_CN.md
> [Doc] Fix github action badge in README

- mmpose/models/distillers/dwpose_distiller.py
> [Fix] Fix bug of dwpose

- configs/wholebody_2d_keypoint/rtmpose/cocktail13/rtmw-x_8xb320-270e_cocktail13-384x288.py
- configs/wholebody_2d_keypoint/rtmpose/cocktail13/rtmw-x_8xb704-270e_cocktail13-256x192.py
- projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb320-270e_cocktail13-384x288.py
- projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb704-270e_cocktail13-256x192.py
> [Fix] Fix new config of RTMW

- mmpose/datasets/datasets/base/base_mocap_dataset.py
- mmpose/datasets/transforms/formatting.py
> [Fix] Refine h36m data loading and add head_size to PackPoseInputs

- mmpose/evaluation/metrics/keypoint_2d_metrics.py
> [Fix] Fix mask shape

- configs/_base_/datasets/humanart21.py
- configs/_base_/datasets/lapa.py
- configs/wholebody_2d_keypoint/rtmpose/cocktail13/rtmw-x_8xb320-270e_cocktail13-384x288.py
- configs/wholebody_2d_keypoint/rtmpose/cocktail13/rtmw-x_8xb704-270e_cocktail13-256x192.py
- mmpose/datasets/datasets/body/__init__.py
- mmpose/datasets/datasets/body/humanart21_dataset.py
- mmpose/datasets/datasets/hand/__init__.py
- mmpose/datasets/datasets/hand/interhand2d_double_dataset.py
- projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb320-270e_cocktail13-384x288.py
- projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb704-270e_cocktail13-256x192.py
- tests/test_datasets/test_datasets/test_body_datasets/test_humanart21_dataset.py
- tests/test_datasets/test_datasets/test_hand_datasets/test_interhand2d_double_dataset.py
> [Feature] Add training datasets of RTMW

- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
> [Doc] update README

- configs/body_2d_keypoint/dekr/coco/dekr_hrnet-w32_8xb10-140e_coco-512x512.py
- configs/body_2d_keypoint/dekr/coco/dekr_hrnet-w48_8xb10-140e_coco-640x640.py
- configs/body_2d_keypoint/dekr/crowdpose/dekr_hrnet-w32_8xb10-300e_crowdpose-512x512.py
- configs/body_2d_keypoint/dekr/crowdpose/dekr_hrnet-w48_8xb5-300e_crowdpose-640x640.py
> [Fix] Add comments in dekr configs for rescore net

- projects/rtmpose/examples/onnxruntime/main.py
In the onnxruntime example for RTMPose, I will encounter an error when using 17 keypoints models. I have made a tiny fix for this problem. 
When drawing the lines, the program would ignore the point index from the `skeleton` that is out of the range of model output.
**Before PR**:
**After PR**:
> [Fix] Let RTMPose onnxruntime example support 17 keypoints model

- configs/wholebody_2d_keypoint/rtmpose/cocktail13/rtmw-x_8xb320-270e_cocktail13-384x288.py
- mmpose/configs/wholebody_2d_keypoint/rtmpose/cocktail13/rtmw-x_8xb320-270e_cocktail13-384x288.py
- mmpose/configs/wholebody_2d_keypoint/rtmpose/cocktail13/rtmw-x_8xb704-270e_cocktail13-256x192.py
- projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb320-270e_cocktail13-384x288.py
- projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb704-270e_cocktail13-256x192.py
MMDeploy has not support new config yet
**Before PR**:
**After PR**:
> [Fix] convert rtmw configs to old version

- docs/en/user_guides/inference.md
- docs/zh_cn/user_guides/inference.md
Add instructions for 3D models.
I was stuck trying to initialize `MMPoseInferencer` with a 3D model alias, only to find out that it had been accepted as a 2D model. Maybe we should tell people to use the `pose3d` parameter.
Add how to use Inferencer with 3d model.
**Before PR**:
**After PR**:
> [Doc] Update inference.md

- configs/body_2d_keypoint/rtmo/crowdpose/rtmo-l_16xb16-700e_crowdpose-640x640.py
- configs/body_2d_keypoint/rtmo/crowdpose/rtmo-m_16xb16-700e_crowdpose-640x640.py
- configs/body_2d_keypoint/rtmo/crowdpose/rtmo-s_8xb32-700e_crowdpose-640x640.py
> [Fix] fix bug in RTMO crowdpose configs

- configs/body_2d_keypoint/rtmo/body7/rtmo-l_16xb16-600e_body7-640x640.py
- configs/body_2d_keypoint/rtmo/body7/rtmo-m_16xb16-600e_body7-640x640.py
- configs/body_2d_keypoint/rtmo/body7/rtmo-s_8xb32-600e_body7-640x640.py
- configs/body_2d_keypoint/rtmo/body7/rtmo-t_8xb32-600e_body7-416x416.py
- configs/body_2d_keypoint/rtmo/coco/rtmo-l_16xb16-600e_coco-640x640.py
- configs/body_2d_keypoint/rtmo/coco/rtmo-m_16xb16-600e_coco-640x640.py
- configs/body_2d_keypoint/rtmo/coco/rtmo-s_8xb32-600e_coco-640x640.py
- configs/body_2d_keypoint/rtmo/coco/rtmo_coco.yml
- configs/body_2d_keypoint/rtmo/crowdpose/rtmo-l_16xb16-700e_crowdpose-640x640.py
- configs/body_2d_keypoint/rtmo/crowdpose/rtmo-m_16xb16-700e_crowdpose-640x640.py
- configs/body_2d_keypoint/rtmo/crowdpose/rtmo-s_8xb32-700e_crowdpose-640x640.py
- configs/body_2d_keypoint/rtmo/crowdpose/rtmo_crowdpose.yml
- mmpose/engine/hooks/mode_switch_hooks.py
> [Fix] fix a bug in RTMOModeSwitchHook

- projects/README.md
> [Doc] Add Pose Anything to projects README

- .owners.yml
> [Fix] update issue owner list

- mmpose/datasets/datasets/wholebody/coco_wholebody_dataset.py
- mmpose/engine/hooks/mode_switch_hooks.py
- projects/rtmo/README.md
- tests/test_engine/test_hooks/test_mode_switch_hooks.py
- tools/slurm_test.sh
- tools/slurm_train.sh
1. polish RTMO homepage
2. fix several bugs in training. The original implementation in `tools/slurm_train.sh` and `tools/slurm_test.sh` do not properly support multiple Python arguments. All Python arguments are treated as a single string. Having more than one argument will result in errors.
**Before PR**:
**After PR**:
> [Doc] Polish RTMO homepage

- README.md
Add recently added Pose Anything project to README file
Add PoseAnything to README file
**Before PR**:
**After PR**:
> [Doc] Add PoseAnything to README file

- docs/en/faq.md
- docs/zh_cn/faq.md
> [Doc] Update FAQ to add instruction on checking keypoint definitions

- mmpose/models/utils/transformer.py
> [Fix] replace `torch.norm` with `torch.linalg.norm` in RTMCCBlock

- projects/rtmpose/app.py
The modified app.py has been tested on OpenXLab
**Before PR**:
**After PR**:
> [Fix] fix RTMPose app

- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
The current documentation for the RTMPose SDK C++ API ([C++ API Documentation](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#c-api)) provides an example for detecting bounding boxes given an image. However, there is a discrepancy compared to the Python API example ([Python API Documentation](https://github.com/open-mmlab/mmpose/tree/main/projects/rtmpose#python-api)), which demonstrates how to use the SDK API for pose detection. This modification would provide users with a consistent and comprehensive understanding of how to use the SDK API for pose detection. ( Close #2885 )
I modified the usage example of C++ API for pose detection (RTMPose), to align it with the corresponding Python API example ([Python API Documentation](https://github.com/open-mmlab/mmpose/tree/main/ …
> [Docs] Refine the C++ API usage example in the RTMPose documentation

- mmpose/structures/pose_data_sample.py
Example in comment was broken Comment 
Fix typo
**Before PR**:
**After PR**:
> [Fix] Typo fix in example comment of pose_data_sample.py

- README.md
- README_CN.md
- docs/en/index.rst
> [Doc] Update "what's new" in README

- configs/body_2d_keypoint/rtmo/body7/rtmo-l_16xb16-600e_body7-640x640.py
- configs/body_2d_keypoint/rtmo/body7/rtmo-m_16xb16-600e_body7-640x640.py
- configs/body_2d_keypoint/rtmo/body7/rtmo-s_8xb32-600e_body7-640x640.py
- configs/body_2d_keypoint/rtmo/body7/rtmo-t_8xb32-600e_body7-416x416.py
- configs/body_2d_keypoint/rtmo/coco/rtmo-l_16xb16-600e_coco-640x640.py
- configs/body_2d_keypoint/rtmo/coco/rtmo-m_16xb16-600e_coco-640x640.py
- configs/body_2d_keypoint/rtmo/coco/rtmo-s_8xb32-600e_coco-640x640.py
- mmpose/apis/inferencers/base_mmpose_inferencer.py
- mmpose/apis/inferencers/pose2d_inferencer.py
- projects/README.md
> [Fix] add RTMO to README and fix some bugs with Inferencer

- CITATION.cff
- README.md
- README_CN.md
- docs/en/faq.md
- docs/en/notes/changelog.md
- docs/zh_cn/faq.md
- docs/zh_cn/notes/changelog.md
- mmpose/__init__.py
- mmpose/version.py
> Bump v1.3.0

- configs/face_2d_keypoint/topdown_regression/wflw/resnet_softwingloss_wflw.yml
- configs/face_2d_keypoint/topdown_regression/wflw/resnet_wflw.yml
- configs/face_2d_keypoint/topdown_regression/wflw/resnet_wingloss_wflw.yml
- tests/test_external/test_mim.py
https://github.com/open-mmlab/mmpose/issues/2918
**Before PR**:
**After PR**:
> [Fix] Fix the error when downloading config and checkpoint using mim

- CITATION.cff
- docs/en/faq.md
- docs/en/notes/changelog.md
- docs/zh_cn/faq.md
- docs/zh_cn/notes/changelog.md
- mmpose/version.py
> Bump v1.3.1

- projects/rtmo/README.md
- projects/rtmpose/README.md
- projects/rtmpose/README_CN.md
- projects/rtmpose/examples/README.md
- projects/rtmpose/examples/rtmlib/README.md
> [Doc] Add rtmlib examples

- docs/en/dataset_zoo/2d_face_keypoint.md
- docs/zh_cn/dataset_zoo/2d_face_keypoint.md
- tools/dataset_converters/wflw2coco.py
Add wflw2coco script, which transform wflw to coco dataset type.
Although it is not same to the originally processed wflw annotations, but the key values are the same and the performance is correct.
> [Feature] add wflw2coco

- docs/en/dataset_zoo/2d_body_keypoint.md
Make the documentation more clear and accurate about the ExLPose dataset.
In the folder structure :
- Properly indented the folder structure to include all `.json` files inside the `annotations/ExLPose` folder.
- usage example of the dataset [here](https://github.com/open-mmlab/mmpose/blob/5a3be9451bdfdad2053a90dc1199e3ff1ea1a409/configs/body_2d_keypoint/topdown_heatmap/exlpose/td-hm_hrnet-w32_8xb64-210e_exlpose-256x192.py#L137)
>  ann_file='annotations/ExLPose/ExLPose_test_LL-A.json',
- Added bright annotations as well as the corresponding image folder
- Renamed examples elements to match original files names
No
No
**Before PR**:
**After PR**:
> [Doc] Improve documentation folder structure of ExLPose

- mmpose/models/heads/heatmap_heads/mspn_head.py
- tests/test_models/test_heads/test_heatmap_heads/test_mspn_head.py
https://github.com/open-mmlab/mmpose/issues/2991
**Before PR**:
**After PR**:
> [Fix] fix loss computation in MSPNHead

- demo/inferencer_demo.py
> [Fix] fix bug in inferencer demo

- docs/en/user_guides/inference.md
> Update inference.md to correct spelling of complere to complete

- docs/zh_cn/dataset_zoo/2d_hand_keypoint.md
The download link of InterHand2.6m is invalid.
Update download link.
**Before PR**:
**After PR**:
> Fix InterHand2.6M annotations download link

- docs/en/user_guides/configs.md
Update in documentation, command to print config
changed command present in docs which is innaccurate
**Before PR**:
**After PR**:
> Update configs.md to fix print config command

- docs/en/index.rst
> Add Mixed Datasets guide to TocTree

- docs/zh_cn/guide_to_framework.md
The missing escape character would treat `_base_` as italics _base_.
Add `\` as escape character for md to recognize correctly.
**Before PR**:
**After PR**:
> add escape character in docs/zh_cn/guide_to_framework.md
