tools/test.py

Thank you for making the code public!
I encountered the error when I evaluated your pretrained model on MS-COCO.
```
(open-mmlab) kimura@kimura-ubuntu-1:~/mot/mmpose$ python tools/test.py configs/top_down/resnet/coco/res50_coco_256x192.py checkpoints/res50_coco_256x192-ec54d7f3_20200709.pth --eval mAP
loading annotations into memory...
Done (t=0.18s)
creating index...
index created!
=> Total boxes: 104125
=> Total boxes after fliter low score@0.0: 104125
=> num_images: 5000
=> load 104125 samples
[>>>>>>>>>>>>>>>>>>>>>] 104125/104125, 59.3 task/s, elapsed: 1756s, ETA:     0sTraceback (most recent call last):
File "tools/test.py", line 120, in <module>
main()
File "tools/test.py", line 116, in main
dataset.evaluate(outputs, args.work_dir, **eval_config)
File …
```

change --eval arg from list to str "mAP"

---

demo/bottom_up_img_demo.py
demo/bottom_up_video_demo.py
demo/top_down_img_demo_with_mmdet.py
docs/getting_started.md
mmpose/apis/__init__.py
mmpose/apis/inference.py
mmpose/core/post_processing/post_transforms.py
mmpose/models/detectors/bottom_up.py
mmpose/models/detectors/top_down.py

Fix https://github.com/open-mmlab/mmpose/issues/29 and fix https://github.com/open-mmlab/mmpose/issues/71

support bottom-up demo

---

mmpose/core/post_processing/post_transforms.py

fix assertion

---

mmpose/models/detectors/top_down.py
tests/test_model/test_top_down_forward.py

add multi-stage loss

---

mmpose/models/backbones/utils/utils.py

wipe out the extra gpu memony cost in dist_train by set the default map_location as 'cpu' , issue#201 https://github.com/open-mmlab/mmpose/issues/201

wipe out the extra gpu memony cost in dist_train

---

demo/bottom_up_img_demo.py
demo/bottom_up_video_demo.py
demo/top_down_img_demo.py
mmpose/apis/inference.py
mmpose/datasets/datasets/bottom_up/bottom_up_coco.py
mmpose/models/detectors/bottom_up.py
mmpose/utils/hooks.py

support return heatmaps and features for bottom-up models

support return heatmaps and features for bottom-up models

---

mmpose/core/post_processing/group.py
mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py
mmpose/datasets/pipelines/bottom_up_transform.py
mmpose/models/backbones/hrnet.py
mmpose/models/backbones/resnet.py
mmpose/models/detectors/bottom_up.py
mmpose/models/detectors/top_down.py
mmpose/models/keypoint_heads/bottom_up_higher_resolution_head.py
mmpose/models/keypoint_heads/bottom_up_simple_head.py
mmpose/models/keypoint_heads/top_down_multi_stage_head.py
mmpose/models/keypoint_heads/top_down_simple_head.py
mmpose/models/losses/mse_loss.py
mmpose/models/mesh_heads/discriminator.py
mmpose/models/mesh_heads/hmr_head.py

Unused vars.

---

mmpose/core/evaluation/mesh_eval.py
mmpose/datasets/datasets/mesh/mesh_h36m_dataset.py

Deleted superfluous-parens

---

mmpose/utils/hooks.py

Explicitly re-raising using the 'from' keyword.

---

demo/2d_hand_demo.md
demo/2d_human_pose_demo.md

fix links for cfg

---

mmpose/models/backbones/shufflenet_v1.py

Simplified if-expression.

---

mmpose/datasets/pipelines/bottom_up_transform.py
mmpose/models/backbones/regnet.py
mmpose/models/backbones/resnet.py

SImplified chained-comparison.

---

mmpose/apis/test.py
mmpose/datasets/datasets/mesh/mesh_mix_dataset.py

Fixed inconsistent-return-statements.

---

mmpose/core/fp16/hooks.py
mmpose/core/post_processing/group.py
mmpose/datasets/datasets/bottom_up/bottom_up_coco.py
mmpose/datasets/datasets/hand/hand_base_dataset.py
mmpose/datasets/datasets/hand/interhand2d_dataset.py
mmpose/datasets/datasets/mesh/mesh_h36m_dataset.py
mmpose/datasets/datasets/mesh/mosh_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py
mmpose/datasets/datasets/top_down/topdown_mpii_trb_dataset.py
mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py
mmpose/datasets/pipelines/bottom_up_transform.py
mmpose/models/backbones/hrnet.py
mmpose/models/backbones/regnet.py
mmpose/models/keypoint_heads/bottom_up_higher_resolution_head.py
mmpose/models/keypoint_heads/bottom_up_simple_head.py
mmpose/models/keypoint_heads/top_down_multi_stage_head.py
mmpose/models/keypoint_heads/top_down_simple_head.py
mmpose/models/losses/mesh_loss.py
mmpose/models/losses/multi_loss_factory.py

no-self-use

---

mmpose/models/backbones/cpm.py
mmpose/models/backbones/hourglass.py
mmpose/models/backbones/hrnet.py
mmpose/models/backbones/mobilenet_v2.py
mmpose/models/backbones/mobilenet_v3.py
mmpose/models/backbones/regnet.py
mmpose/models/backbones/resnet.py
mmpose/models/backbones/scnet.py
mmpose/models/backbones/shufflenet_v1.py
mmpose/models/backbones/shufflenet_v2.py
mmpose/models/backbones/utils/inverted_residual.py

Protect against dangerous default value.

---

mmpose/models/backbones/__init__.py
mmpose/models/backbones/mspn.py
mmpose/models/backbones/utils/utils.py
tests/test_backbones/test_mspn.py

Add mspn backbone and its unit test.

Add mspn backbone

---

.pylintrc

Usage
```bash
pylint mmpose
```
Currently this is added for convenience.
On current master:
```bash
************* Module mmpose.core.post_processing.group
mmpose/core/post_processing/group.py:317:12: W0632: Possible unbalanced tuple unpacking with sequence defined at line 2 of : left side has 2 label(s), right side has 1 value(s) (unbalanced-tuple-unpacking)
mmpose/core/post_processing/group.py:378:12: C0200: Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
************* Module mmpose.core.evaluation.eval_hooks
mmpose/core/evaluation/eval_hooks.py:99:8: C0415: Import outside toplevel (mmpose.apis.single_gpu_test) (import-outside-toplevel)
mmpose/core/evaluation/eval_hooks.py:169:8: C0415: Import outside toplevel (mmpose.apis.multi_gpu_test) …
```

Add pylint rc file

---

mmpose/datasets/datasets/top_down/topdown_mpii_trb_dataset.py

rm unnecessary comments

---

mmpose/datasets/pipelines/bottom_up_transform.py
mmpose/datasets/pipelines/mesh_transform.py
mmpose/datasets/pipelines/shared_transform.py
mmpose/datasets/pipelines/top_down_transform.py
tests/test_compose.py

pylint remove object from bases

---

requirements/runtime.txt

had to add some deps to the requirements to get a working installation. See https://github.com/open-mmlab/mmpose/issues/282

udpate reqs with missing deps

---

docs/install.md
requirements/readthedocs.txt

Fix https://github.com/open-mmlab/mmpose/issues/311

Use mmcv-full

---

mmpose/datasets/datasets/top_down/topdown_aic_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py
mmpose/datasets/datasets/top_down/topdown_crowdpose_dataset.py
mmpose/datasets/datasets/top_down/topdown_ochuman_dataset.py
mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py

add use_nms option

---

.github/workflows/build.yml
docs/tutorials/export_model.md
requirements/optional.txt
tests/test_onnx.py
tools/pytorch2onnx.py

Support Onnx

---

.github/workflows/build.yml

Fix #330.
Reply from mmcv: pytorch1.4 has too many bugs, so only pre-built version is provided.

Removed torch1.4 from CI.

---

docs/stat.py
requirements/readthedocs.txt
setup.cfg

Titlecase in stats

---

configs/hand/mobilenet_v2/README.md
configs/hand/mobilenet_v2/onehand10k/mobilenetv2_onehand10k_256x256.py
configs/hand/mobilenet_v2/panoptic/mobilenetv2_panoptic_256x256.py

add mobilenet v2 onehand10k & panoptic

add mobilenet hand

---

README.md
configs/top_down/resnest/README.md
configs/top_down/resnest/coco/resnest101_coco_256x192.py
configs/top_down/resnest/coco/resnest101_coco_384x288.py
configs/top_down/resnest/coco/resnest50_coco_256x192.py
configs/top_down/resnest/coco/resnest50_coco_384x288.py
configs/top_down/vgg/README.md
configs/top_down/vgg/coco/vgg16_bn_coco_256x192.py
mmpose/models/backbones/__init__.py
mmpose/models/backbones/resnest.py
mmpose/models/backbones/vgg.py
tests/test_backbones/test_resnest.py
tests/test_backbones/test_vgg.py

The codes are from MMClassification.

add resnest and vgg backbone

---

configs/top_down/mspn/coco/2xmspn50_coco_256x192.py
configs/top_down/mspn/coco/3xmspn50_coco_256x192.py
configs/top_down/mspn/coco/4xmspn50_coco_256x192.py
configs/top_down/mspn/coco/mspn50_coco_256x192.py
mmpose/models/backbones/mspn.py

pretrained_model for mspn.
fix #395

mspn_pretrained_model

---

configs/top_down/resnet/coco/res50_coco_256x192.py
configs/top_down/resnet/posetrack18/res50_posetrack18_256x192.py
mmpose/apis/train.py
mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py
mmpose/datasets/datasets/top_down/topdown_jhmdb_dataset.py
mmpose/datasets/datasets/top_down/topdown_mpii_dataset.py
mmpose/datasets/datasets/top_down/topdown_mpii_trb_dataset.py
mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py
mmpose/datasets/pipelines/shared_transform.py
mmpose/models/detectors/top_down.py
tests/test_datasets/test_top_down_dataset.py
tests/test_model/test_top_down_forward.py
tests/test_pipelines/test_top_down_pipelines.py
tools/test.py

Topdown multi batch inference
fix #25
fix #120
fix #197

Topdown multi batch inference

---

mmpose/core/post_processing/post_transforms.py

Setting all joint scores to be 0 would cause erroneous results in testing for bottom-up approach

fix bugs in bottom-up keypoint score

---

mmpose/apis/train.py
mmpose/core/fp16/decorators.py
setup.cfg

* import Fp16OptimizerHook from mmcv if its version>=1.3.1
* add deprecation warning to Fp16OptimizerHook, auto_fp16 and force_fp32

Swith to fp16 hooks in mmcv

---

mmpose/datasets/pipelines/bottom_up_transform.py
requirements/optional.txt
tests/test_pipelines/test_bottom_up_pipelines.py

* opencv-python 4.5.2 compatibility
BottomUpRandomAffine fails with opencv-python>=4.5.2 because a \
single valued numpy.ndarray is no longer a valid data type for \
image_size in cv2.warpAffine. This commit fix it by repacing   \
image_size with image_size.item().
* smplx 0.1.27 compatibility
smplx>=0.1.27 requires loguru, which will not be automatically installed \
when installing smplx. So we add loguru into mmpose requirements.

Fix opencv 4.5.2 compatibility

---

mmpose/apis/inference.py

When running demo with UDP like below, 
```
python demo/top_down_img_demo.py  \
configs/top_down/udp/coco/hrnet_w32_coco_256x192_udp.py  \https://download.openmmlab.com/mmpose/top_down/udp/hrnet_w32_coco_256x192_udp-aba0be42_20210220.pth \
--img-root tests/data/coco/ \
--json-file tests/data/coco/test_coco.json --out-img-root vis_results
```
this error happened, and demo failed.
```
Traceback (most recent call last):
File "demo/top_down_img_demo.py", line 104, in <module>
main()
File "demo/top_down_img_demo.py", line 85, in main
outputs=output_layer_names)
File "program/mmpose/mmpose/apis/inference.py", line 401, in inference_top_down_pose_model
return_heatmap=return_heatmap)
File "program/mmpose/mmpose/apis/inference.py", line 297, in _inference_single_pose_model
data = …
```

fix demo/top_down_img_demo.py with UDP

---

tools/train.py

When resuming training, MMCV calculates the iteration from the gpu_ids, which is not available in the distributed mode. This PR provides a workaround to re-set gpu_ids according to the world_size in this case.

Fix GPU_IDS in distributed training

---

requirements/optional.txt
requirements/runtime.txt

When installing mmpose with mim, the packages in optional.txt will not be installed. But when I try to import mmpose.apis, the package poseval will be imported. So it should be moved into runtime.txt.

Fix dependency

---

demo/docs/3d_human_pose_demo.md

- updated path from "configs/body/3d_kpt_sview_rgb_img/simple_baseline_3d/h36m/simple3Dbaseline_h36m.py " to "configs/body/3d_kpt_sview_rgb_img/pose_lift/h36m/simplebaseline3d_h36m.py"
- Because the file "simple3Dbaseline_h36m.py" does not exist in that path now.

fixed incorrect path in 3d_human_pose_demo.md

---

demo/docs/2d_animal_demo.md
demo/docs/2d_human_pose_demo.md
demo/docs/2d_pose_tracking_demo.md
demo/docs/2d_wholebody_pose_demo.md

Change model download links from http to https to avoid chrome prompting download errors.

Change to https

---

requirements/readthedocs.txt

In titlecase>=2.1.0, if `regex` is not successfully imported, `re` will be imported as `regex`, which may lead to unexpected behavior or errors. So we add regex into the requirements explicitly.

Add regex dependency

---

demo/docs/3d_human_pose_demo.md

Previously an h36m 2d model was used in the 3d human pose demo example, which was reported by #777  to have poor results. We found this is because the h36m 2d model generalizes poorly to in-the-wild images. Thus we recommend using COCO 2d pose model instead and update the demo example in this PR.

Use COCO 2D pose model in 3D demo examples

---

mmpose/datasets/datasets/top_down/topdown_mpii_dataset.py

[bug fix] fix mpii pckh 0.1 index

---

mmpose/apis/test.py

`/tmp` dir is usually not shared in the cluster environment. Therefore it's better to use a local tmpdir to store the test result.
refs:
- https://github.com/open-mmlab/mmdetection/pull/4017
- https://github.com/open-mmlab/mmaction2/pull/292
- https://github.com/open-mmlab/mmclassification/pull/251

Fix multi-node distributed test

---

requirements/optional.txt

By default, installing `albumentations` by pip has `opencv-python-headless` dependency even if `opencv-python` has already been installed. This could cause different opencv versions installed in the environment and lead to unexpected errors.
This PR updates the installation of `albumentations` to prevent using a wheel distribution of it with `opencv-python-headless` dependency. See its [docs](https://albumentations.ai/docs/getting_started/installation/#note-on-opencv-dependencies) for details.

Remove opencv-python-headless dependency by albumentations

---

tools/deployment/pytorch2onnx.py

This PR fixes the issue that `pytorch2onnx.py` loads pre-trained backbone weights in `build_posenet` before loading actual checkpoints.
We have tested that the updated and the original scripts have identical outputs.

Update pytorch2onnx.py to avoid redundant weight loading

---

.github/workflows/build.yml

Fix cuda installation error in CI.
Change `runs-on` from ubuntu-latest to ubuntu-18.04.
**Before PR**:
**After PR**:

fix runs-on as ubuntu-18.04 to avoid cuda installation error

---

.dev_scripts/benchmark/benchmark_cfg.yaml
.dev_scripts/benchmark/benchmark_regression.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vipnas_coco.md
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/vipnas_coco.yml

Add default test and train arguments in the script. Add mode field to the parser, can choose `test` or `train`.
Modify .`dev_scripts/benchmark/benchmark_regression.py`
```
cd $mmpose
python .dev_scripts/benchmark/benchmark_regression.py --partition mm_human --mode test --priority 2 
```
or
```
cd $mmpose
python .dev_scripts/benchmark/benchmark_regression.py -p mm_human --mode train --priority 1
```
Note that the `--partition` or `-p` field is necessary. The `priority` can be specified depending on the `mode` field.

Modify the benchmark regression script

---

mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py
mmpose/datasets/datasets/top_down/topdown_aic_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py
mmpose/datasets/datasets/top_down/topdown_crowdpose_dataset.py
mmpose/datasets/datasets/top_down/topdown_h36m_dataset.py
mmpose/datasets/datasets/top_down/topdown_jhmdb_dataset.py
mmpose/datasets/datasets/top_down/topdown_mhp_dataset.py
mmpose/datasets/datasets/top_down/topdown_mpii_trb_dataset.py
mmpose/datasets/datasets/top_down/topdown_ochuman_dataset.py
mmpose/datasets/datasets/top_down/topdown_posetrack18_dataset.py

Fix #915.
In case that we forget to assign the key `ann_info['use_different_joint_weights']`, we move it from all topdown dataset classes to the very base class, `Kpt2dSviewRgbImgTopDownDataset`. 
Add the following code  `self.ann_info['use_different_joint_weights'] = False` in `mmpose/mmpose/datasets/datasets/base/kpt_2d_sview_rgb_img_top_down_dataset.py`.
And also remove this code from all related classes:
```
mmpose/mmpose/datasets/datasets/top_down/topdown_aic_dataset.py
mmpose/mmpose/datasets/datasets/top_down/topdown_coco_dataset.pyy
mmpose/mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py
mmpose/mmpose/datasets/datasets/top_down/topdown_crowdpose_dataset.p
mmpose/mmpose/datasets/datasets/top_down/topdown_h36m_dataset.py …
```

[Fix] move the key `use_different_joint_weights` to Kpt2dSviewRgbImgTopDownDataset

---

docs/collect.py
docs_zh-CN/collect.py

Ignore _base_ configs when counting ckpt/cfg.
**Before PR**:
**After PR**:

[Fix] ignore _base_ in collections

---

requirements/optional.txt
requirements/runtime.txt

`trimesh` was imported after #771 and was added into `optional.txt`. However, it dit not using `try` to avoid rasing error when not installing this package.  **This led to the failure of CI for downstream projects**.
Add `trimesh` and `poseval` to `requirements/runtime.txt`
None.
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.
**Before PR**:
**After PR**:

[Fix]: Fix requirements.

---

mmpose/apis/train.py
tools/test.py

Fix #923 
the bugs in #926 are fixed
Related PRs: https://github.com/open-mmlab/mmocr/pull/459
Follow https://github.com/open-mmlab/mmocr/blob/main/mmocr/apis/train.py to refactor the collection of the config for training/testing.
**Before PR**:
**After PR**:

[Feature] Support multiple settings for data_loader

---

mmpose/apis/inference.py
mmpose/datasets/pipelines/bottom_up_transform.py
tests/test_pipelines/test_bottom_up_pipelines.py

The current version requires the input of a bottom-up model to have a square shape (w=h). This pr is to enable the pipeline of bottom-up approaches to take inputs with any w-h ratio.
mmpose/datasets/pipelines/bottom_up_transform.py
**Before PR**:
**After PR**:

nonsquare input shape for bottom_up

---

mmpose/models/backbones/mobilenet_v3.py

Fix typo in mobilenet_v3 backbone
Modify `$mmpose/models/backbones/mobilenet_v3.py` to delete the reduplicate initialization and allow ``-1'' to indicates output tensors from final stage.
**Before PR**:
**After PR**:

[Enhancement] Support minus output feature index in mobilenet_v3

---

demo/mmtracking_cfg/deepsort_faster-rcnn_fpn_4e_mot17-private-half.py
demo/top_down_pose_tracking_demo_with_mmtracking.py

The result key of mmtracking has changed from `track_results` to `track_bboxes`.
This PR will update it and support demo with the recent mmtracking.
Also the config of another popular mot algorithm (deepsort) is added.
**Before PR**:
**After PR**:

[Fix] Update pose tracking demo to be compatible with latest mmtrakcing

---

mmpose/core/visualization/image.py
mmpose/models/detectors/top_down.py

Fix an unexpected behavior (introduced by #1009) that a bbox without a label will be marked as 'unknown', instead of shown with no label.
**Before PR**:
**After PR**:

[Fix] Fix bbox label visualization

---

.dev_scripts/benchmark/benchmark_cfg_flops_speed.yaml
.dev_scripts/benchmark/flops_test.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnext101_coco_256x192.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnext101_coco_384x288.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnext152_coco_256x192.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnext152_coco_384x288.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnext50_coco_256x192.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/coco/resnext50_coco_384x288.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnext101_mpii_256x256.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnext152_mpii_256x256.py
configs/body/2d_kpt_sview_rgb_img/topdown_heatmap/mpii/resnext50_mpii_256x256.py
tools/analysis/get_flops.py

1. Add model list for flops and speed test, mainly focusing on models on `configs/body/2d_kpt_sview_rgb_img`, with three types:  `topdown_heatmap`, `associative embedding` and `DeepPose`.
2. Change the `bulid_posenet` function to `init_pose_model`, which is a more clean API.
3. Update some outdated paths to checkpoints.
**Before PR**:
**After PR**:

[Fix] Add cfg file for flops and speed test, and fix some typo in related scripts and config file

---

demo/docs/2d_animal_demo.md
demo/docs/2d_face_demo.md
demo/docs/2d_hand_demo.md

Fix #1037 about the dead links.
**Before PR**:
**After PR**:

[Fix] fix dead links

---

.github/workflows/build.yml

Skip CI when some specific files were changed to save the CI resources.
More details can be found at https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths.
Update .github/workflows/build.yml
**Before PR**:
**After PR**:

[Enhancement] Skip CI when some specific files were changed

---

setup.py

Fix the building failure issue on Windows caused by failing to create symbol links for mim extensions.
Reference:  [mmdet-#6480](https://github.com/open-mmlab/mmdetection/issues/6480).
Try to catch the exception raised by ```os.symlink``` on Windows
**Before PR**:
**After PR**:

[Fix] Catch symlink failure on Windows

---

.circleci/config.yml
.github/workflows/build.yml
.github/workflows/lint.yml
.pre-commit-config.yaml

- Support CircleCI
- Use the official markdownlint hook
- Fix uncompleted part of #1041 
- Add `.circleci/config.yml`
- Add `.github/workflows/lint.yml`
- Modify `.github/workflows/built.yml'` to remove lint check
- Modify `.pre-commit-config.yaml` to use offical markdownlint hook
**Before PR**:
**After PR**:

[Enhancement] Support circleci and fix lint check

---

mmpose/datasets/pipelines/loading.py

Support file_client_args in LoadImageFromFile. Similar to this in mmdet:
https://github.com/open-mmlab/mmdetection/blame/0b94be76b89fcbbfd83ef2a1a67818b5948280d1/mmdet/datasets/pipelines/loading.py#L12
LoadImageFromFile in loading.py
**Before PR**:
**After PR**:

[Feature] Support file_client_args in LoadImageFromFile

---

tools/webcam/webcam_apis/webcam_runner.py

[WebcamAPI] Fix typing compatibility

---

docs/faq.md
mmpose/core/evaluation/top_down_eval.py
tests/test_evaluation/test_top_down_eval.py

Met a bug when training with udp, look like this
```
error: (-215:Assertion failed) top >= 0 && bottom >= 0 && left >= 0 && right >= 0 && _src.dims() <= 2 in function 'cv::copyMakeBorder'
```
Review the code and find that cv2.copMakeBorder will report an error when input dimension exceeds 512
In the raw code, the author directly use cv2.copyMakeBorder to operate batch of heatmaps and it crashed
The tested opencv-python version is 4.5.4.60, 4.4.0.40, 4.1.0.25, all have this problem
Complete environmental information is like this
```
Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: Tesla P40
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, …
```

[Fix] Bug in post dark udp

---

README.md
README_CN.md
configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/res50_wflw_256x256_softwingloss.py
configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/resnet_softwingloss_wflw.md
configs/face/2d_kpt_sview_rgb_img/deeppose/wflw/resnet_softwingloss_wflw.yml
docs/papers/techniques/softwingloss.md
mmpose/models/losses/__init__.py
mmpose/models/losses/regression_loss.py
model-index.yml
tests/test_losses/test_regression_losses.py

Support SoftWingLoss. 
"Structure-Coherent Deep Feature Learning for Robust Face Alignment" TIP'2021
**Before PR**:
**After PR**:

[Feature] Soft wing loss (TIP'2021)

---

demo/bottom_up_pose_tracking_demo.py
demo/bottom_up_video_demo.py
demo/face_video_demo.py
demo/top_down_pose_tracking_demo_with_mmdet.py
demo/top_down_pose_tracking_demo_with_mmtracking.py
demo/top_down_video_demo_full_frame_without_det.py
demo/top_down_video_demo_with_mmdet.py

Run the demo code in remote machine without cam.
Add args.show checking in demo/foo.py 
**Before PR**:
**After PR**:

[Fix] Don't destroy NULL windows if args.show == False

---

mmpose/core/evaluation/top_down_eval.py

Fix #1100 
Using `np.pad` will make the codes much cleaner. 
But it is a little bit slower. In my tests, the old vs the new  is 0.004 ms vs 0.04 ms. 
```
batch_heatmaps = np.transpose(batch_heatmaps,
(2, 3, 0, 1)).reshape(H, W, -1)
batch_heatmaps_channel = batch_heatmaps.shape[2]
if batch_heatmaps_channel > 512:
total_group_number = int(np.ceil(batch_heatmaps_channel / 512))
splited_batch_heatmaps = []
for group_idx in range(total_group_number):
splited_batch_heatmap = batch_heatmaps[
..., group_idx *
512:min(batch_heatmaps_channel, (group_idx + 1) * 512)]
batch_heatmap_pad = cv2.copyMakeBorder(
splited_batch_heatmap,
1,
1,
1,
1,
borderType=cv2.BORDER_REFLECT)
splited_batch_heatmaps.append(batch_heatmap_pad)
batch_heatmaps_pad = np.concatenate(splited_batch_heatmaps, axis=2)
else: …
```

[Fix] Use np.pad

---

docs/en/getting_started.md

fix bugs
**Before PR**:
**After PR**:

[Doc] Update getting_started.md

---

mmpose/datasets/builder.py
tests/test_datasets/test_dataset_wrapper.py

[Feature] Support Concat dataset

---

tools/webcam/webcam_apis/nodes/frame_effect_nodes.py
tools/webcam/webcam_apis/utils/misc.py

The node can draw a sprite chasing your eyes. (At first, I want it to chase hands, but I don't know how to get hand keypoints :joy: )
As the title
```python
dict(
type='SpriteNode',
name='sprite',
enable_key='s',
frame_buffer='vis',
output_buffer='sprite'),
```
**Before PR**:
**After PR**:

[Feature] Add a `SpriteNode` for Webcam API

---

mmpose/apis/inference.py
mmpose/core/post_processing/group.py
mmpose/core/post_processing/nms.py
tests/test_post_processing/test_group.py
tests/test_post_processing/test_nms.py

#1169 
* Add a param score_per_joint in the HeatmapParser group algorithm
* Change ok_nms algorithm to take this into consideration
No
See #1169 
**Before PR**:
**After PR**:

[Feature] Support score_per_joint in group and nms

---

requirements/optional.txt

By default, installing `albumentations` by pip has `opencv-python-headless` dependency even if `opencv-python` has already been installed. This could cause different opencv versions installed in the environment and lead to unexpected errors. 
https://github.com/open-mmlab/mmpose/pull/833 has fixed this potential issue, but `albumentations` has updated their installing way, which changes 
`pip install albumentations --no-binary imgaug,albumentations` 
to 
`pip install -U albumentations --no-binary qudida,albumentations`. See its [docs](https://albumentations.ai/docs/getting_started/installation/#note-on-opencv-dependencies) for details.

[Fix] update albumentations installed way

---

mmpose/apis/inference_tracking.py

Fix the calculation of bounding box area (#1194).
- Corrected the way `result['area']` is calculated
**Before PR**:
**After PR**:

Fix bbox area calculation in inference tracking (#1194)

---

tools/deployment/mmpose2torchserve.py
tools/deployment/mmpose_handler.py
tools/deployment/pytorch2onnx.py
tools/deployment/test_torchserver.py

Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in future.
Add deprecation message in deployment tools.
Used package [colorama](https://github.com/tartley/colorama#colored-output) to print cross-platform colored text.
**Before PR**:
**After PR**:

Add deprecation message for deploy tools

---

.github/workflows/build.yml
tests/test_backbones/test_hourglass.py
tests/test_models/test_voxelpose.py

Add Windows CI.
- Add Windows CI in GitHub workflow.
- Modify some unittest parameters to reduce memory cost in Windows CI.
**Before PR**:
**After PR**:

[Feature] Add Windows CI

---

mmpose/core/visualization/image.py
tests/test_visualization.py

fix for issue https://github.com/open-mmlab/mmpose/issues/1227
joints with color=None should be skipped according to the documentation:
https://github.com/open-mmlab/mmpose/blob/c09a6930a2e699722ec3bd6142c6ad334d32b469/mmpose/core/visualization/image.py#L126

[Fix] skip joints that should be hidden in visualization

---

mmpose/apis/train.py

There is no reason to ignore custom_hooks.
**Before PR**:
**After PR**:

[Fix] complete training hooks.

---

mmpose/models/backbones/utils/channel_shuffle.py

If we use **`pytorch2onnx.py`** to generate ONNX with the batch size set to a variable size of **`-1`**, it will generate a model that cannot be inferred by onnxruntime because the **`Reshape`** operation on ONNX will include two **`-1`** in the modified shape. **`(1)`** in the figure below. The ONNX model shown below will cause an error in onnxruntime if the batch size is changed to **`-1`**. Because onnxruntime does not allow more than two dimensions of variable size.
- Sample ONNX file just before initializing batch size
[litehrnet_18_coco_Nx256x192_reshape_channel=-1.onnx.zip](https://github.com/open-mmlab/mmpose/files/8254335/litehrnet_18_coco_Nx256x192_reshape_channel.-1.onnx.zip)
The ONNX model output after applying this modification is shown below. The batch size is initialized to …

[Fix] Changed channel size from -1 to an operable number "channel_shuffle"

---

mmpose/core/utils/__init__.py
mmpose/core/utils/dist_utils.py
mmpose/datasets/samplers/distributed_sampler.py

This PR fixes a potential bug introduced in #1229 
- #1229 allows using different random seeds for different ranks, which may cause trouble for DistributedSampler because data shuffle results will be different across ranks.
- This PR syncs random seed (only) in DistributedSampler to fix the problem.
Refer to https://github.com/open-mmlab/mmdetection/pull/7432/ and https://github.com/open-mmlab/mmdetection/pull/7440
**Before PR**:
**After PR**:

[Fix] sync random seed in DistributedSamplers

---

.dev_scripts/github/update_model_index.py

Related PR: https://github.com/open-mmlab/mmsegmentation/pull/1407. 
In Windows OS, the pre-commit would generate model-index.yml with Windows path style, which is not compatible with Linux. 
1. Use `.replace('\\', '/')` for path.
3. Explicitly use `encoding='utf-8'` when reading md files.
**Before PR**:
**After PR**:

[Fix] Fix Windows style path in Windows pre-commit

---

demo/body3d_two_stage_video_demo.py

Fixing a typo in the function definition
This is the second PR I opened for this issue, closed the first one because of the username mismatch with CLA.
Changed ```covert_keypoint_definition``` to ```convert_keypoint_definition```
**Before PR**:
**After PR**:

[FIX] fixing typo in function definition in 3d demo

---

mmpose/models/detectors/associative_embedding.py
mmpose/models/detectors/mesh.py
mmpose/models/detectors/multi_task.py
mmpose/models/detectors/pose_lifter.py
mmpose/models/detectors/top_down.py
tests/test_models/test_bottom_up_forward.py
tests/test_models/test_mesh_forward.py
tests/test_models/test_multitask_forward.py
tests/test_models/test_pose_lifter_forward.py
tests/test_models/test_top_down_forward.py

The motivation of this PR is to compatible with mme in model loading pretrained. MME will call `init_weights` function without input parameter in the training script, which will overwrite the loaded pretrained model parameters. 
- detector  
Modify the `pretrained` parameter to an attribute of the detector model. And `init_weights` function preferentially uses the incoming `pretrained`. If there are no input parameters, the attribute `self.pretrained` is used.
No
**Before PR**:
**After PR**:

[Fix] Compatible with mme in model loading pretrained.

---

mmpose/core/post_processing/group.py
tests/test_post_processing/test_group.py

Fix: https://github.com/open-mmlab/mmpose/issues/1336
**Before PR**:
**After PR**:

[Fix] Fix bug of human skeleton grouping for params.ignore_too_much

---

mmpose/datasets/datasets/animal/animal_ap10k_dataset.py
mmpose/datasets/datasets/animal/animal_atrw_dataset.py
mmpose/datasets/datasets/animal/animal_macaque_dataset.py
mmpose/datasets/datasets/animal/animal_pose_dataset.py
mmpose/datasets/datasets/bottom_up/bottom_up_coco.py
mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
tests/test_datasets/test_animal_dataset.py
tests/test_datasets/test_bottom_up_dataset.py
tests/test_datasets/test_top_down_dataset.py

When the ground truth keypoint annotations are absent, the evaluation will end with a confusing error message like: 
`AttributeError: 'COCOeval' object has no attribute 'score_key' `.
1. Add warning message in coco evaluation function. 
2. Skip 
```python
tmp_folder.cleanup()
```
to save the results json file if it is saved under `tmp_folder`.
**Before PR**:
**After PR**:

[Fix] Add warning message in coco evaluation when gt annotations are absent

---

mmpose/datasets/datasets/animal/animal_ap10k_dataset.py
mmpose/datasets/datasets/animal/animal_atrw_dataset.py
mmpose/datasets/datasets/animal/animal_macaque_dataset.py
mmpose/datasets/datasets/animal/animal_pose_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_dataset.py
mmpose/datasets/datasets/top_down/topdown_coco_wholebody_dataset.py
mmpose/datasets/datasets/top_down/topdown_jhmdb_dataset.py
mmpose/datasets/datasets/top_down/topdown_posetrack18_video_dataset.py

Fix #1333 
**Before PR**:
**After PR**:

[Fix] xywh->xyxy calculation in sanity check

---

demo/docs/2d_animal_demo.md
demo/docs/2d_human_pose_demo.md
demo/top_down_video_demo_full_frame_without_det_gpuaccel.py

It's a parallel to my ![mmdetection PR](https://github.com/open-mmlab/mmdetection/pull/7832).
The video inference was not efficient, because there are many "resize", "padding", "to rgb" and "normalize" operations in CPU workload. Besides, the 'img_metas' is calculated for every frame, which is nonefficient. The CPU workload is really high, but the speed is slow.
I transformed the video "crop", "resize", "padding", "to rgb" in ffmpeg-based video reader, which is lite and CPU friendly. The video reader can support NVIDIA-VIDEO-DECODING if possible, to save more CPU workload. And the "normalize" is done in GPU. In all, I reduced the data-loading time and CPU workload.
For the pure data loading, it can reach 400 Fps (possible the ceiling of NVIDIA-DECODER). The CPU work load is acceptable …

[Enhance] Speedup the Video Inference by Accelerating data-loading Stage in Top_Down_Full_Frame_without_Det

---

mmpose/apis/inference.py
tests/test_apis/test_inference.py
tools/webcam/configs/examples/pose_tracking.py
tools/webcam/webcam_apis/nodes/__init__.py
tools/webcam/webcam_apis/nodes/frame_drawing_node.py
tools/webcam/webcam_apis/nodes/helper_node.py
tools/webcam/webcam_apis/nodes/mmdet_node.py
tools/webcam/webcam_apis/nodes/mmpose_node.py
tools/webcam/webcam_apis/nodes/node.py
tools/webcam/webcam_apis/nodes/pose_tracker_node.py

Support pose tracking in webcam API for faster pose estimation (FPS: 4.5 to 7.0; lag: 400ms -> 200ms).
- Add ``PoseTrackerNode``
- Add config `tools\webcam\configs\examples\pose_tracking.py`
- Minor modification to some webcam nodes
- Fix a bug in model inference (add ``TopDownGetBboxCenterScale`` if it's missing in the original pipeline)
**Before PR**:
**After PR**:

[Feature] support pose tracking in webcam API

---

mmpose/apis/inference_tracking.py

The `get_track_id()` function in `inference_tracking.py` has a `min_keypoints` parameter that promises:
```
min_keypoints (int): Minimum number of keypoints recognized as person.
```
For the default value of 3, this means that all detected poses with 3 or more keypoints start a new track if it is not matched above a threshold to an existing track. The implementation has an off-by-one error though meaning in this case only detected poses with 4 or more keypoints will start a new track:
```
if np.count_nonzero(result['keypoints'][:, 1]) > min_keypoints:
```
This is unexpected/unclear for the user of the function.
The obvious solution is to change `>` to `>=`, but this leads to a problem when `min_keypoints` is zero, so it needs to become:
```
if min_keypoints <= 0 or …
```

Adjust inference tracking min keypoints

---

configs/hand/gesture_sview_rgbd_vid/mtut/nvgesture/i3d_nvgesture_224x224_fps30.py
configs/hand/gesture_sview_rgbd_vid/mtut/nvgesture/i3d_nvgesture_bbox_112x112_fps15.py
configs/hand/gesture_sview_rgbd_vid/mtut/nvgesture/i3d_nvgesture_bbox_112x112_fps15_rgb.py
configs/hand/gesture_sview_rgbd_vid/mtut/nvgesture/i3d_nvgesture_bbox_224x224_fps30.py
mmpose/apis/train.py

Change 'custom_hooks_config' to 'custom_hooks' in configs following the OpenMMLab convention. Compatibility to the old-style config is handled.
**Before PR**:
**After PR**:

[Fix] rename `custom_hooks_config` to `custom_hooks`

---

docs/en/tutorials/6_customize_runtime.md
docs/zh_cn/tutorials/6_customize_runtime.md
mmpose/core/__init__.py
mmpose/core/optimizer/__init__.py
mmpose/core/optimizers/__init__.py
mmpose/core/optimizers/builder.py
mmpose/core/optimizers/layer_decay_optimizer_constructor.py
tests/test_core/test_layer_decay_optimizer_constructor.py
tests/test_core/test_optimizer.py
tests/test_models/test_mesh_forward.py

1. Add layer decay optimizer constructor 
2. Add learning rate decay optimizer constructor
These two optimizers will be used in BEiT, MAE, ViT, ConvNeXt backbones. 
The codes are from mmsegmentation.
Related PRs: https://github.com/open-mmlab/mmsegmentation/commit/f16bb060923a2dcb638e84eb96dbf7fc8c1dbb9b
1. rename mmpose/core/optimizer --> mmpose/core/optimizers
2. Add mmpose/core/optimizers/layer_decay_optimizer_constructor.py
3. move tests/test_optimizer.py to tests/test_core/test_optimizer.py
**Before PR**:
**After PR**:

[Feature] Add layer decay optimizer constructor and learning rate decay optimizer constructor

---

configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w32_atrw_256x256.py
configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/hrnet_w48_atrw_256x256.py
configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res101_atrw_256x256.py
configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res152_atrw_256x256.py
configs/animal/2d_kpt_sview_rgb_img/topdown_heatmap/atrw/res50_atrw_256x256.py
configs/hand/2d_kpt_sview_rgb_img/deeppose/panoptic2d/res50_panoptic2d_256x256.py
configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic2d_256x256.py
configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic2d_256x256_dark.py
configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/hrnetv2_w18_panoptic2d_256x256_udp.py
configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/mobilenetv2_panoptic2d_256x256.py
configs/hand/2d_kpt_sview_rgb_img/topdown_heatmap/panoptic2d/res50_panoptic2d_256x256.py
requirements/docs.txt

1. Modify typos in related configs.
2. Modify the `requirements/dics.txt`. Refer to https://github.com/open-mmlab/mmcv/pull/2121, otherwise the documentation can not be built.
**Before PR**:
**After PR**:

[Fix] Fix some typos in configs

---

mmpose/core/utils/tensor_utils.py
mmpose/models/heads/base_head.py
mmpose/models/heads/heatmap_heads/heatmap_head.py
mmpose/models/heads/regression_heads/regression_head.py

Refactor `HeatmapHead` and `BaseHead` class
Reorganized `decode`, `_get_in_channels`, `_transform_inputs` into `BaseHead`.
Modified `decode` for supporting `heatmap-based`, `regression-based` and `integral-regression` methods. Support heatmap visualization config via `test_cfg`.
Saved `_to_numpy` as a util function in /core/utils/tensor_utils.py
**Before PR**:
**After PR**:

[Refactor] Reorganize HeatmapHead and BaseHead class in order to develop RegressionHead

---

demo/bottom_up_pose_tracking_demo.py
mmpose/apis/inference_tracking.py
tests/test_apis/test_inference_tracking.py

Fix: https://github.com/open-mmlab/mmpose/issues/1502
**Before PR**:
**After PR**:

[Fix] fix bug of non-COCO dataset track demo

---

.github/workflows/build.yml
requirements/albu.txt
requirements/optional.txt
setup.py

Without it, users who are used to install mmlab packages will automatically add the "optional" extra and will encounter a pip error
Added the missing extra of "optional" as seen in other MM repos as mmaction2  (https://github.com/open-mmlab/mmaction2/blob/master/setup.py#L193)   and mmdetection  (https://github.com/open-mmlab/mmdetection/blob/master/setup.py#L216)

Added the 'Optional' extra require in setup.py

---

mmpose/codecs/simcc_label.py
mmpose/models/heads/heatmap_heads/heatmap_head.py
mmpose/models/heads/heatmap_heads/simcc_head.py
mmpose/models/heads/regression_heads/integral_regression_head.py
mmpose/models/heads/regression_heads/regression_head.py
mmpose/models/heads/regression_heads/rle_head.py
mmpose/models/utils/tta.py
tests/test_models/test_heads/test_heatmap_heads/test_simcc_head.py
tests/test_models/test_heads/test_regression_heads/test_dsnt_head.py
tests/test_models/test_heads/test_regression_heads/test_integral_regression_head.py
tests/test_models/test_heads/test_regression_heads/test_regression_head.py
tests/test_models/test_heads/test_regression_heads/test_rle_head.py

Support test time augmentation by flipping for regression heads (`RegressionHead`, `RLEHead`, `DSNTHead` and `IntegralRegressionHead`)
Support test time augmentation by flipping for simcc heads (`SimCCHead`)
**Before PR**:
**After PR**:

[Refactor] support flip test for regression and simcc heads

---

configs/body_2d_keypoint/topdown_heatmap/aic/hrnet_w32_aic_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/hrformer_small_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/litehrnet_18_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/mobilenetv2_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/mspn50_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/pvt-s_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/rsn18_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/swin_t_p4_w7_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/vipnas_mbv3_coco_256x192.py
configs/body_2d_keypoint/topdown_heatmap/crowdpose/hrnet_w32_crowdpose_256x192.py
mmpose/evaluation/metrics/coco_metric.py

Add configs for top-down heatmap models on COCO, AIC, CrowdPose. The performance of these models matches that on logs
1. Add configs for top-down heatmap models on COCO, AIC, CrowdPose.
2. Fix `CocoMetric` to support customized `iou_type`
**Before PR**:
**After PR**:

[Refactor] Add verified configs for topdown heatmap models with CocoMetric

---

mmpose/core/post_processing/post_transforms.py
tests/test_post_processing.py

- Fix bug when `joints_3d_visible` has float values
- `TopDownRandomFlip` transformation will output wrong joints coordinates if  `joints_3d_visible` has float values
- Make `joints_3d_visible_flipped` be 0 or 1 during random flip
**Before PR**:
**After PR**:

Fix fliplr_joints bug when joints_3d_visible has float values

---

configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_2xmspn50_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_2xrsn50_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_3xmspn50_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_3xrsn50_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_4xmspn50_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_mspn50_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_rsn18_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_rsn50_8xb32-210e_coco-256x192.py
mmpose/datasets/transforms/common_transforms.py
mmpose/datasets/transforms/formatting.py
mmpose/models/heads/heatmap_heads/mspn_head.py
mmpose/structures/multilevel_pixel_data.py
mmpose/structures/pose_data_sample.py
mmpose/testing/_utils.py
tests/test_datasets/test_transforms/test_common_transforms.py
tests/test_models/test_heads/test_heatmap_heads/test_mspn_head.py
tests/test_structures/test_multilevel_pixel_data.py
tests/test_structures/test_pose_data_sample.py

1. Unify the `multiscale`, `multi-scale`, `multi-level` to `multilevel`; add `multilevel_gt_fields` in `PoseDataSample`;
2. Modify `MSPNHead` to fit `MultilevelPixelData`;
3. Fix some bugs in `MultilevelPixelData` add unittests for `MultilevelPixelData`;
4. Modify the MSPNd and RSN configs according to the above modificatios.
All unitetsts passed locally.
The test accuracy for `configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_2xmspn50_8xb32-210e_coco-256x192.py` is verified, will also verify other modified configs.
**Before PR**:
**After PR**:

[Refactor] Modify some scripts to fit `MultilevelPixelData`

---

mmpose/apis/webcam/utils/buffer.py
mmpose/engine/hooks/visualization_hook.py
mmpose/visualization/local_visualizer.py
tests/test_engine/test_hooks/test_visualization_hook.py
tests/test_visualization/test_pose_visualizer.py
tools/misc/browse_dataset.py

1. fix a bug about visualizer's dataset_meta.
When testing with multiple GPUs, there are multiple processes but only one `visualizer`. The `visualizer.dataset_meta` is manually set to `None` occasionally in some processes in test_loop. This may lead to `AttributeError` in other processes when getting items from `visualizer.dataset_meta`.
3. refine dataset browser
- use `file_client` to read image instead of `mmcv.imread`
- keep `bbox_file` in dataset configs. Thus the visualization results match the images model receives indeed.
**Before PR**:
**After PR**:

[Fix] Fix a visualization bug and refine dataset browser

---

demo/topdown_demo_with_mmdet.py
demo/topdown_face_demo.py
mmpose/visualization/local_visualizer.py

1. Support nms-thr in `topdown_demo_with_mmdet.py`;
2. Fix use `keypoint_scores` to filter keypoints to be visualized.
**Before PR**:
**After PR**:

[Fix] Fix  keypoint_scores in visualization

---

.circleci/config.yml
.circleci/test.yml
.pre-commit-config.yaml
mmpose/apis/webcam/utils/buffer.py

The motivation to upgrade some versions of pre-commit hooks to latest is that importlib-metadata v5.0.0 which removed deprecated endpoint breaks the flake8
**Before PR**:
**After PR**:

[Fix] Upgrade the versions of pre-commit-hooks

---

configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_udp-regress-8xb64-210e_coco-256x192.py
mmpose/codecs/utils/offset_heatmap.py
mmpose/models/heads/heatmap_heads/heatmap_head.py
mmpose/models/heads/heatmap_heads/vipnas_head.py
mmpose/models/losses/__init__.py

Fix loss in udp_regress.
**Before PR**:
**After PR**:

[Fix] Fix udp regress

---

configs/animal_2d_keypoint/topdown_heatmap/README.md
configs/face_2d_keypoint/topdown_heatmap/README.md
configs/hand_2d_keypoint/topdown_heatmap/README.md
configs/hand_2d_keypoint/topdown_regression/README.md
configs/wholebody_2d_keypoint/topdown_heatmap/README.md

Update `topdown_heatmap` and `topdown_regression` algorithm readmes with performance tables for animal / face / hand / wholebody configs.
**Before PR**:
**After PR**:

[Doc] Update algorithm readmes with performance tables

---

mmpose/__init__.py
mmpose/version.py
requirements/poseval.txt

[Refactor] Specify mmengine version

---

mmpose/datasets/pipelines/shared_transform.py

there is 'f-string' missing in Albumentation transforms.
just simply add 'f'......
**Before PR**:
**After PR**:

[Fix] fix f-string missing in shared_transform.py

---

configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_hrnet-w32_8xb64-210e_ap10k-256x256.py
configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_hrnet-w48_8xb64-210e_ap10k-256x256.py
configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_res101_8xb64-210e_ap10k-256x256.py
configs/animal_2d_keypoint/topdown_heatmap/ap10k/td-hm_res50_8xb64-210e_ap10k-256x256.py
mmpose/datasets/datasets/base/base_coco_style_dataset.py
mmpose/datasets/transforms/formatting.py
mmpose/evaluation/functional/nms.py
mmpose/evaluation/metrics/__init__.py
mmpose/evaluation/metrics/coco_metric.py
mmpose/evaluation/metrics/posetrack18_metric.py
tests/test_evaluation/test_metrics/test_coco_metric.py

Support evaluating coco metric without ann_file thus other non-COCO format datasets can take CocoMetric as well.
1. Add the `'CLASSES'` in the dataset metainfo to store the information about category.
2. Add  `'raw_ann_info'` key in the definition of `BaseCocoStyleDataset`
3. Add  `'raw_ann_info'` key in `mmpose/datasets/transforms/formatting.py`
4. Modify `CocoMetric`, add `gt_to_coco_json` function. Also fix the inheritance dependency of `PoseTrack18Metric`
5. Add unittests.
In order to use this function, we need to change some places:
1.  Add `'raw_ann_info'` to the data_info in the dataset to store the raw annotation information:
```python
data_info = {
'img_id': ann['image_id'],
'img_path': img_path,
'bbox': bbox,
'bbox_score': np.ones(1, dtype=np.float32),
'num_keypoints': …
```

 [Feature] Support evaluating CocoMetric without ann_file.

---

mmpose/datasets/transforms/common_transforms.py

Same as #1716 
The original results of data info may contain the key like `keypoints` which may trigger unexpected functions and raise error in albu like `apply_to_keypoint`.
Modify `mmpose/datasets/transforms/common_transforms.py`, only map those keys that are specified in keymap_to_albu to albu format.
**Before PR**:
**After PR**:

[Fix] Avoid mapping unnecessary key to albu format

---

configs/_base_/datasets/coco_aic.py
configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_coco_aic.md
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-aic-256x192-combine.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-aic-256x192-merge.py
docs/en/user_guides/prepare_datasets.md
mmpose/apis/inference.py
mmpose/datasets/__init__.py
mmpose/datasets/dataset_wrappers.py
mmpose/datasets/transforms/__init__.py
mmpose/datasets/transforms/converting.py
mmpose/models/pose_estimators/base.py
mmpose/models/pose_estimators/topdown.py
tests/test_datasets/test_datasets/test_dataset_wrappers/test_combined_dataset.py
tests/test_datasets/test_transforms/test_converting.py

Support training with combined datasets
1. add a new dataset wrapper `CombinedDataset`
2. add `KeypointConverter` to convert the channel order of `keypoints` and `keypoints_visible`
3. add unittests
4. add two example configs
- `td-hm_hrnet-w32_8xb64-210e_coco-aic-256x192-merge.py` maps the keypoints of AIC to COCO format.\
- `td-hm_hrnet-w32_8xb64-210e_coco-aic-256x192-combine.py` maps the keypoints of AIC & COCO to a combined format. 
5. modify default `dataset_meta` in `init_cfg` from test dataset to train dataset
**Before PR**:
**After PR**:

[Enhance] Support training with combined datasets

---

mmpose/apis/webcam/nodes/model_nodes/pose_estimator_node.py

The metainfo item `'CLASSES'` in MMPose has a different format from that in MMDectection. This conflict will lead to an error illustrated in https://github.com/open-mmlab/mmpose/issues/1812.
In [`TopDownPoseEstimatorNode`](https://github.com/open-mmlab/mmpose/blob/dev-1.x/mmpose/apis/webcam/nodes/model_nodes/pose_estimator_node.py), use the values from detector metainfo for overlapped keys instead of the values from pose estimator metainfo.
**Before PR**:
**After PR**:

[Fix] Fix webcam metainfo

---

demo/docs/2d_animal_demo.md
demo/docs/2d_face_demo.md
demo/docs/2d_hand_demo.md
demo/docs/2d_human_pose_demo.md
demo/docs/2d_wholebody_pose_demo.md
demo/topdown_demo_with_mmdet.py
demo/topdown_face_demo.py
demo/webcam_cfg/pose_estimation.py
mmpose/structures/__init__.py
mmpose/structures/utils.py

Add an option `--save-predictions` in demo scripts. 
If activated, the predicted results will be saved under the directory given by `--output-root`
**Before PR**:
**After PR**:

[Enhance] Support saving predictions in topdown demos

---

docs/src/papers/techniques/rle.md

Add rle.md in papers/techniques/
**Before PR**:
**After PR**:

[Docs] Fix link in the modelzoo (dev1.x)

---

projects/README.md
projects/example_project/README.md
projects/example_project/configs/example-head-loss_hrnet-w32_8xb64-210e_coco-256x192.py
projects/example_project/models/__init__.py
projects/example_project/models/example_head.py
projects/example_project/models/example_loss.py

1. add readme for projects
2. add an example project in which a head and a loss are customized
3. add readme for example project
**Before PR**:
**After PR**:

[Project] Add example project

---

docs/en/user_guides/configs.md
docs/zh_cn/migration.md
docs/zh_cn/user_guides/configs.md

[Docs] refine docs

---

mmpose/datasets/__init__.py
mmpose/datasets/dataset_wrappers.py

[Fix] fix bug in CombinedDataset and remove RepeatDataset

---

mmpose/datasets/datasets/base/base_coco_style_dataset.py
mmpose/datasets/datasets/body/mpii_dataset.py
mmpose/datasets/datasets/body/mpii_trb_dataset.py
mmpose/datasets/datasets/hand/coco_wholebody_hand_dataset.py
mmpose/evaluation/metrics/coco_metric.py
tests/test_datasets/test_datasets/test_dataset_wrappers/test_combined_dataset.py
tests/test_datasets/test_datasets/test_face_datasets/test_coco_wholebody_face_dataset.py

The initial implementation of bottom-up datasets fails to take into account images lacking instance annotations, thus deviating from the standard evaluation protocol and resulting in an inflated accuracy score.
1. Modify `_load_annotations` in `BaseCocoStyleDataset`, `MpiiDataset`, `MpiiTrbDataset` and `CocoWholeBodyDataset` to support returning both instance list and image list
2. Modify `BaseCocoStyleDataset._get_bottomup_data_infos` to add images without instance into `data_list_bu`
3. Update `CocoMetric` to adapt the above modifications
4. Update unittests 
**Before PR**:
**After PR**:

[Fix] Include images without instance into bottom-up datasets for validation

---

mmpose/datasets/builder.py

Since `RepeatDataset` has been removed in #1930, the import statement in https://github.com/open-mmlab/mmpose/blob/525fdb78e369c6448f5224c8bd57b1e33a5f1898/mmpose/datasets/builder.py#L67 will raise an `ImportError`
**Before PR**:
**After PR**:

[Fix] fix datasets import error

---

docs/en/user_guides/codecs.md
docs/zh_cn/user_guides/codecs.md

[Docs] update codec docs

---

docs/en/notes/faq.md
docs/zh_cn/notes/faq.md

[Fix] update mmcv/mmengine compatibility information in FAQ

---

configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-base_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-base_8xb32-210e_coco-384x288.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-small_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrformer-small_8xb32-210e_coco-384x288.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_swin-l-p4-w7_8xb32-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_swin-l-p4-w7_8xb32-210e_coco-384x288.py
mmpose/models/backbones/swin.py

- Fix misplaced `paramwise_cfg` in configs
- Fix a bug in swin backbone initialization
**Before PR**:
**After PR**:

[Fix] fix config and code errors of swin/hrformer

---

mmpose/datasets/dataset_wrappers.py
mmpose/datasets/datasets/base/base_coco_style_dataset.py

[Fix] copy metainfo in get_data_info

---

projects/rtmpose/benchmark/README.md
projects/rtmpose/benchmark/README_CN.md

add benchmark result of running rtmpose for coco-wholebody on GTX-3090.
only benchmark file of rtmpose
no
**Before PR**:
**After PR**:

[Doc] add benchmark result of running rtmpose for coco-wholebody on GTX-3090

---

tools/misc/publish_model.py

[Feature] Remove ema and message_hub when publishing models

---

configs/_base_/datasets/coco_aic.py
docs/en/advanced_guides.md
docs/en/advanced_guides/mixed_datasets.md
docs/en/index.rst
docs/zh_cn/advanced_guides.md
docs/zh_cn/advanced_guides/mixed_datasets.md
docs/zh_cn/index.rst

[Docs] Doc about using CombinedDataset

---

demo/topdown_demo_with_mmdet.py
mmpose/apis/webcam/nodes/model_nodes/detector_node.py
mmpose/utils/__init__.py
mmpose/utils/config_utils.py

While inferring top-down models on videos, the scope alternates between 'mmdet' and 'mmpose' repeatedly, which often results in numerous warning messages.
**Before PR**:
**After PR**:

[Fix] Avoid scope switching when using mmdet inference interface

---

mmpose/datasets/transforms/common_transforms.py

[Fix] Fix repeated warning from different ranks

---

configs/body_2d_keypoint/topdown_heatmap/coco/vitpose_coco.yml
docs/src/papers/backbones/vitpose.md
model-index.yml

[Fix] Add metafile and paper information of ViTPose

---

mmpose/engine/__init__.py
mmpose/registry.py

This PR fixes the warnings raised when falling back to mmengine registries (registries without registered modules in mmpose).
**Before PR**:
**After PR**:

[Fix] fix warnings when falling back to mmengine registry

---

configs/animal_2d_keypoint/topdown_heatmap/ap10k/resnet_ap10k.yml
configs/face_2d_keypoint/topdown_heatmap/wflw/hrnetv2_wflw.yml
configs/hand_2d_keypoint/topdown_heatmap/onehand10k/resnet_onehand10k.yml

[Fix] fix model names in metafiles

---

mmpose/visualization/simcc_vis.py

Fix 1d heatmap visualization problem,  change  the method of generating background image from：
```
blank = np.zeros((size[0] * 2, size[1] * 2, 3), np.uint8)
```
to:
```
blank_height = int(
max(size[0] * 2, size[0] * 1.1 + (K + 1) * (15 + interval)))
blank_width = int(
max(size[1] * 2, size[1] * 1.1 + (K + 1) * (15 + interval)))
blank = np.zeros((blank_height, blank_width, 3), np.uint8)
```

[Fix] fix 1d heatmap visualization  problem

---

demo/inferencer_demo.py

需要把inferencer_demo.py中的--det-cat-ids参数默认设置为0，否则检测不到关键点，建议修改一下。

[Fix] Set default det-cat-ids for inferencer_demo.py

---

configs/_base_/datasets/coco_openpose.py
demo/image_demo.py
demo/topdown_demo_with_mmdet.py
mmpose/apis/inferencers/base_mmpose_inferencer.py
mmpose/engine/hooks/visualization_hook.py
mmpose/visualization/local_visualizer.py
projects/mmpose4aigc/openpose_visualization.py

add `--skeleton-style` to `image_demo.py` and `topdown_demo_with_mmdet.py`
For Example:
```shell
python demo/topdown_demo_with_mmdet.py \
${MMDET_CONFIG_FILE} ${MMDET_CHECKPOINT_FILE} \
${MMPOSE_CONFIG_FILE} ${MMPOSE_CHECKPOINT_FILE} \
--input ${INPUT_PATH} \
--skeleton-style openpose \
--show
```
The result is as follow:
**Before PR**:
**After PR**:

[Feature] Visualize openpose skeleton style on the image

---

tools/train.py

Fix the problem regarding `local-rank` in PyTorch 2.0
**Before PR**:
**After PR**:

[Fix] Fix accepting an unexpected argument `local-rank` in PyTorch 2.0

---

configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-base-simple_8xb64-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-huge-simple_8xb64-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-large-simple_8xb64-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_ViTPose-small-simple_8xb64-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_cpm_8xb32-210e_coco-384x288.py
configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_cpm_8xb64-210e_coco-256x192.py
configs/body_2d_keypoint/topdown_heatmap/jhmdb/td-hm_cpm_8xb32-40e_jhmdb-sub1-368x368.py
configs/body_2d_keypoint/topdown_heatmap/jhmdb/td-hm_cpm_8xb32-40e_jhmdb-sub2-368x368.py
configs/body_2d_keypoint/topdown_heatmap/jhmdb/td-hm_cpm_8xb32-40e_jhmdb-sub3-368x368.py
configs/body_2d_keypoint/topdown_heatmap/mpii/td-hm_cpm_8xb64-210e_mpii-368x368.py
mmpose/models/heads/coord_cls_heads/simcc_head.py
mmpose/models/heads/heatmap_heads/ae_head.py
mmpose/models/heads/heatmap_heads/cpm_head.py
mmpose/models/heads/heatmap_heads/heatmap_head.py
mmpose/models/heads/heatmap_heads/vipnas_head.py
mmpose/models/heads/regression_heads/dsnt_head.py
mmpose/models/heads/regression_heads/integral_regression_head.py
tests/test_models/test_heads/test_heatmap_heads/test_ae_head.py
tests/test_models/test_heads/test_heatmap_heads/test_cpm_head.py
tests/test_models/test_heads/test_heatmap_heads/test_heatmap_head.py
tests/test_models/test_heads/test_heatmap_heads/test_vipnas_head.py
tests/test_models/test_heads/test_regression_heads/test_dsnt_head.py
tests/test_models/test_heads/test_regression_heads/test_integral_regression_head.py

replace the `has_final_layer` argument with the `final_layer` argument, which is a dictionary containing the parameters for the final conv2d layer.
**Before PR**:
**After PR**:

[Refactor] refactor final layer in heads

---

mmpose/apis/inferencers/pose2d_inferencer.py

To allow the `demo/inferencer_demo.py` to utilize models from mmyolo for object detection in top-down pose estimation.
```shell
python demo/inferencer_demo.py tests/data/coco/000000000785.jpg --pose2d human \
--det-model ${MMYOLO_PATH}/configs/yolox/yolox_tiny_fast_8xb8-300e_coco.py \
--det-weights https://download.openmmlab.com/mmyolo/v0/yolox/yolox_tiny_8xb8-300e_coco/yolox_tiny_8xb8-300e_coco_20220919_090908-0e40a6fc.pth \
--show
```
**Before PR**:
**After PR**:

[Enhance] Inferencer support mmyolo detector

---

configs/body_2d_keypoint/topdown_heatmap/coco/hrnet_coco.yml
demo/inferencer_demo.py
docs/en/user_guides/inference.md
mmpose/apis/inferencers/__init__.py
mmpose/apis/inferencers/utils/__init__.py
mmpose/apis/inferencers/utils/get_model_alias.py

[Enhance] Support displaying alias in Inferencer demo and refine docs

---

demo/MMPose_Tutorial.ipynb
mmpose/models/pose_estimators/base.py
mmpose/models/utils/__init__.py
mmpose/models/utils/check_and_update_config.py
tests/test_models/test_utils/test_check_and_update_config.py

#2108 and #2126 modified the interface of neck and head. If users use the latest mmpose and old configs, there might be some conflict.
1. add a function `check_and_update_config` that checks if the config is consistent with the latest mmpose. If not, the arguments will be automatically updated. In addition, this function will display the guide for updating the configs, such as 
and
2. add unit test for  `check_and_update_config`
3. verify the test accuracy of `cid_hrnet-w32_8xb20-140e_coco-512x512`, `td-hm_ViTPose-base-simple_8xb64-210e_coco-256x192`, `td-hm_pvt-s_8xb64-210e_coco-256x192`
**Before PR**:
**After PR**:

[Refactor] add config checker

---

README_CN.md
docs/en/installation.md
docs/zh_cn/installation.md

[Docs] Update Installation Guides

---

README.md
README_CN.md

[Docs] add migration progress

---

mmpose/datasets/datasets/base/base_coco_style_dataset.py
mmpose/datasets/datasets/body/mpii_dataset.py
mmpose/datasets/datasets/body/mpii_trb_dataset.py
mmpose/datasets/datasets/body/posetrack18_video_dataset.py
mmpose/datasets/datasets/hand/coco_wholebody_hand_dataset.py
mmpose/evaluation/metrics/coco_metric.py

[Refactor] Add petrel file reading function from MMEngine

---

README.md
README_CN.md
projects/README.md
projects/awesome-mmpose/README.md
projects/rtmpose/README.md
projects/rtmpose/README_CN.md

[Docs] Refine README

---

docs/en/how_to.md
docs/en/user_guides/configs.md
docs/zh_cn/how_to.md
docs/zh_cn/user_guides/configs.md

[Docs] update Config docs

---

configs/face_2d_keypoint/topdown_regression/README.md
configs/face_2d_keypoint/topdown_regression/wflw/resnet_wflw.md
configs/face_2d_keypoint/topdown_regression/wflw/resnet_wflw.yml
configs/face_2d_keypoint/topdown_regression/wflw/td-reg_res50_8x64e-210e_wflw-256x256.py

MMSIG-92
configs/face_2d_keypoint/topdown_regression/wflw/td-reg_res50_8x64e-210e_wflw-256x256.py
configs/face_2d_keypoint/topdown_regression/wflw/README.md
**Before PR**:
**After PR**:

[MMSIG-92] Integrate WFLW deeppose model to dev-1.x branch

---

docs/zh_cn/user_guides/inference.md

[Doc] refine inference doc

---

demo/MMPose_Tutorial.ipynb

MMPose_Tutorial.ipynb output an error at runtime. Therefore, I fixed it.
Two modifications are as follows
- Return value of _load_annotations()
- The caller of the _load_annotations function expects two values to be returned, but the code before the modification returned only one value. Therefore, this was changed to return two values. However, the second return value is not used by the caller, so None is returned.
- Metrics
- There was no "pck/PCK@0.0" metric, so I corrected it to "PCK".
**Before PR**:
**After PR**:

[Fix] config param and return values of functions in the dataset class in the tutorial 

---

README.md
README_CN.md
mmpose/structures/bbox/transforms.py

fix `mmpose/structures/bbox/transforms.py` `bbox_cs2xywh` comments

[Docs] update bbox_cs2xywh comments

---

demo/body3d_pose_lifter_demo.py
mmpose/apis/inference_3d.py
mmpose/visualization/local_visualizer_3d.py

Fix the problem of accidentally detecting multiple bboxes.
**Before PR**:
**After PR**:

[Fix] Fix bugs in 3d human pose demo

---

demo/docs/2d_animal_demo.md
demo/docs/2d_hand_demo.md
demo/docs/2d_human_pose_demo.md
demo/docs/2d_pose_tracking_demo.md
demo/docs/2d_wholebody_pose_demo.md
demo/docs/3d_human_pose_demo.md
requirements/mminstall.txt

[Fix] Restrict mmdet version to avoid conflict when using mmpose 0.x

---

mmpose/models/backbones/hrformer.py

As illustrated in https://github.com/open-mmlab/mmpose/issues/2448, applying `revert_sync_batchnorm` on HRFormer does not convert the BNs within the `self.layers` list in the FFN modules. Consequently, this triggers a RuntimeError during the inference process.
1. remove the attribute `layers` in FFN module
2. rewrite the forward process
**Before PR**:
**After PR**:

[Fix] Remove the native list attribute `self.layers` in HRFormer FFN modules

---

demo/inferencer_demo.py
mmpose/apis/inferencers/base_mmpose_inferencer.py
mmpose/apis/inferencers/mmpose_inferencer.py
mmpose/apis/inferencers/pose2d_inferencer.py
mmpose/apis/inferencers/pose3d_inferencer.py

[Enhance] Support Openpose skeleton style in inferencer

---

configs/_base_/datasets/coco_openpose.py
demo/inferencer_demo.py
mmpose/apis/inferencers/base_mmpose_inferencer.py
mmpose/apis/inferencers/mmpose_inferencer.py
mmpose/apis/inferencers/pose2d_inferencer.py
mmpose/visualization/local_visualizer.py
mmpose/visualization/opencv_backend_visualizer.py

```bash
python demo/inferencer_demo.py tests/data/coco/000000000785.jpg \
--pose2d human --vis-out-dir vis_results \
--skeleton-style openpose --black-background --radius 4 --thickness 4
```
The above command will generate this result:
**Before PR**:
**After PR**:

[Enhance] Inferencer supports visualization black background

---

docs/en/dataset_zoo/dataset_tools.md
docs/en/dataset_zoo/label_studio.md
docs/zh_cn/dataset_zoo/dataset_tools.md
docs/zh_cn/dataset_zoo/label_studio.md
tools/dataset_converters/labelstudio2coco.py

A tool to convert label studio's json annotation results to coco format.
Add a single python script file.
```bash
python tools/dataset_converters/labelstudio2coco.py config.xml project-1-at-2023-05-13-09-22-91b53efa.json output/result.json
```
The `config.xml` is from `Labeling Interface` in label studio web ui. The content is like that:
```xml
<View>
<KeyPointLabels name="kp-1" toName="img-1">
<Label value="person" background="#D4380D"/>
</KeyPointLabels>
<PolygonLabels name="polygonlabel" toName="img-1"> 
<Label value="person" background="#0DA39E"/>
</PolygonLabels>
<RectangleLabels name="label" toName="img-1"> 
<Label value="person" background="#DDA0EE"/>
</RectangleLabels>
<Image name="img-1" value="$img"/>
</View>
```
The `project-*.json` is from `Export` -> `JSON` in label studio …

[Feature] Add tool for converting label studio json result to coco format

---

README.md
README_CN.md
docs/src/papers/datasets/human_art.md
docs/src/papers/datasets/lapa.md

[Docs] Update docs and readme

---

mmpose/datasets/transforms/common_transforms.py
mmpose/datasets/transforms/formatting.py
mmpose/models/heads/__init__.py
mmpose/models/heads/hybrid_heads/__init__.py
mmpose/models/heads/hybrid_heads/vis_head.py
mmpose/models/losses/__init__.py
mmpose/models/losses/classification_loss.py
mmpose/models/utils/tta.py
tests/test_models/test_heads/test_hybrid_heads/test_vis_head.py

Enable top-down methods to predict keypoints visibility
1. add a new head `vis_head` in hybrid_heads      (mmpose/mmpose/models/heads/hybrid_heads/vis_head.py)
2. add a new TTA function `flip_visibility`     (mmpose/mmpose/models/utils/tta.py)
3. add a new key `transformed_keypoints_visible` in `label_mapping_table` (mmpose/mmpose/datasets/transforms/formatting.py)
4. support `keypoints_visible` in `GenerateTarget` (mmpose/mmpose/datasets/transforms/common_transforms.py)
5. <s>add a new loss function `BCEWithLogitsLoss` (mmpose/mmpose/models/losses/classification_loss.py)</s>
6.  refine `BCELoss` module: add parameter `with_logits` to decide whether to use BCEWithLogitsLoss  (mmpose/mmpose/models/losses/classification_loss.py)
7. add unittest for `vis_head` …

[Feature] Add visibility prediction head

---

mmpose/evaluation/functional/keypoint_eval.py

If the keypoint accuracy is 0, the function `keypoint_pck_accuracy` will return an integer `0` instead of a float, leading to the bug reported in https://github.com/open-mmlab/mmpose/issues/2372
**Before PR**:
**After PR**:

[Fix] fix returned variable type in keypoint_pck_accuracy

---

docs/en/user_guides/inference.md
docs/zh_cn/user_guides/inference.md

https://github.com/open-mmlab/mmpose/issues/2494
**Before PR**:
**After PR**:

[Doc] Add example of inference on multiple images using inferencer

---

demo/body3d_pose_lifter_demo.py
demo/docs/en/3d_human_pose_demo.md
mmpose/visualization/local_visualizer_3d.py

[Fix] 3d pose demo with multiple instances

---

projects/README.md
projects/rtmpose/README.md
projects/rtmpose/README_CN.md

[Docs] Update YOLOX-Pose link and RTMPose Docs

---

mmpose/apis/inferencers/pose3d_inferencer.py

[Fix] fix keypoint shape bug in Pose3dInferencer

---

configs/body_3d_keypoint/pose_lift/h36m/motionbert_h36m.md
configs/body_3d_keypoint/pose_lift/h36m/motionbert_h36m.yml
configs/body_3d_keypoint/pose_lift/h36m/pose-lift_motionbert-243frm_8xb32-120e_h36m-original.py
configs/body_3d_keypoint/pose_lift/h36m/pose-lift_motionbert-243frm_8xb32-120e_h36m.py
configs/body_3d_keypoint/pose_lift/h36m/pose-lift_motionbert-ft-243frm_8xb32-60e_h36m-original.py
configs/body_3d_keypoint/pose_lift/h36m/pose-lift_motionbert-ft-243frm_8xb32-60e_h36m.py
mmpose/codecs/motionbert_label.py
mmpose/datasets/transforms/pose3d_transforms.py
mmpose/models/heads/regression_heads/motion_regression_head.py
mmpose/models/losses/__init__.py
mmpose/models/pose_estimators/pose_lifter.py
tests/test_codecs/test_motionbert_label.py
tests/test_datasets/test_transforms/test_pose3d_transforms.py

[Fix] MotionBERT training and flip-test

---

demo/body3d_pose_lifter_demo.py
demo/docs/en/3d_human_pose_demo.md

[Refactor] 3d human pose demo

---

mmpose/apis/inferencers/pose2d_inferencer.py
mmpose/apis/inferencers/pose3d_inferencer.py
tests/test_apis/test_inferencers/test_pose2d_inferencer.py

If the input for the inferencer is a folder and the `vis_out_dir` dumping argument is a file name, only the most recent visualization results will be saved in the end.
**Before PR**:
**After PR**:

[Fix] Check the compatibility of inferencer's input/output 

---

projects/README.md
projects/just_dance/README.md

[Doc] Add example and OpenXLab link for Just Dance

---

docs/en/advanced_guides/how_to_deploy.md
docs/en/advanced_guides/implement_new_models.md
docs/en/advanced_guides/model_analysis.md
docs/en/index.rst
docs/en/user_guides/how_to_deploy.md
docs/zh_cn/advanced_guides/how_to_deploy.md
docs/zh_cn/advanced_guides/implement_new_models.md
docs/zh_cn/advanced_guides/model_analysis.md
docs/zh_cn/index.rst
docs/zh_cn/user_guides/how_to_deploy.md

[Docs] Add deployment docs

---

mmpose/structures/bbox/transforms.py

[Fix] Fix bug in `flip_bbox` with xyxy format

---

configs/_base_/datasets/ubody2d.py
configs/wholebody_2d_keypoint/topdown_heatmap/README.md
configs/wholebody_2d_keypoint/topdown_heatmap/ubody2d/hrnet_coco-wholebody.yml
configs/wholebody_2d_keypoint/topdown_heatmap/ubody2d/hrnet_ubody-coco-wholebody.md
configs/wholebody_2d_keypoint/topdown_heatmap/ubody2d/td-hm_hrnet-w32_8xb64-210e_ubody-256x192.py
docs/en/dataset_zoo/2d_wholebody_keypoint.md
docs/en/dataset_zoo/dataset_tools.md
docs/src/papers/datasets/ubody.md
mmpose/datasets/datasets/base/base_coco_style_dataset.py
mmpose/datasets/datasets/wholebody/__init__.py
mmpose/datasets/datasets/wholebody/ubody2d_dataset.py
mmpose/evaluation/metrics/coco_wholebody_metric.py
tools/dataset_converters/ubody_kpts_to_coco.py
tools/test.py

Support ubody dataset.
Official repo: https://github.com/IDEA-Research/OSX
**Before PR**:
**After PR**:

[Feature] Support ubody dataset (2d keypoints)

---

demo/body3d_pose_lifter_demo.py
mmpose/apis/inference_3d.py

[Fix] Visualization problems in 3d demo

---

demo/body3d_pose_lifter_demo.py
demo/docs/en/3d_human_pose_demo.md

[Fix] 3d human pose demo argument `use-multi-frames`

---

docs/en/user_guides/inference.md
docs/zh_cn/user_guides/inference.md
mmpose/apis/inferencers/base_mmpose_inferencer.py
mmpose/apis/inferencers/mmpose_inferencer.py
mmpose/apis/inferencers/pose2d_inferencer.py
mmpose/apis/inferencers/pose3d_inferencer.py
projects/just_dance/process_video.py
tests/test_apis/test_inferencers/test_mmpose_inferencer.py
tests/test_apis/test_inferencers/test_pose2d_inferencer.py
tests/test_apis/test_inferencers/test_pose3d_inferencer.py
tests/test_datasets/test_transforms/test_common_transforms.py

[Fix] Fix inferencer argument name

---

mmpose/datasets/datasets/base/base_coco_style_dataset.py
mmpose/datasets/transforms/formatting.py
mmpose/evaluation/metrics/coco_metric.py
tests/test_evaluation/test_metrics/test_coco_metric.py
tests/test_evaluation/test_metrics/test_coco_wholebody_metric.py
tests/test_evaluation/test_metrics/test_keypoint_partition_metric.py

[Enhance] Enable CocoMetric to get ann_file from MessageHub

---

mmpose/structures/utils.py

[Fix] fix bug in merge_data_samples after refactoring PackInputs

---

configs/body_2d_keypoint/edpose/coco/edpose_coco.md
configs/body_2d_keypoint/edpose/coco/edpose_coco.yml
configs/body_2d_keypoint/edpose/coco/edpose_res50_8xb2-50e_coco-800x1333.py

[Fix] Unify test batch_size of edpose

---

docs/en/guide_to_framework.md
docs/zh_cn/guide_to_framework.md

[Docs] Refine dataset config tutorial

---

mmpose/apis/inferencers/pose3d_inferencer.py

[Fix] Fix 3d inferencer to improve performance with videopose3d

---

demo/docs/en/3d_hand_demo.md
demo/hand3d_internet_demo.py
mmpose/visualization/local_visualizer_3d.py

[Feature] Add demo script for 3d hand pose 

---

demo/docs/en/3d_hand_demo.md
demo/hand3d_internet_demo.py
mmpose/datasets/datasets/__init__.py

[Fix] Fix Internet demo

---

mmpose/visualization/local_visualizer_3d.py

[Fix] Color discrepancy in 3d demos

---

mmpose/datasets/transforms/converting.py
mmpose/evaluation/functional/__init__.py
mmpose/evaluation/functional/transforms.py
mmpose/evaluation/metrics/coco_metric.py
tests/test_datasets/test_transforms/test_converting.py
tests/test_evaluation/test_functional/test_transforms.py

[Refactor] Separate evaluation mappings from KeypointConverter

---

mmpose/codecs/motionbert_label.py

[Fix] MotionbertLabel codec

---

mmpose/models/heads/hybrid_heads/vis_head.py

As mentioned in [issues/2799](https://github.com/open-mmlab/mmpose/issues/2799), when shape of vis_weights is also [N,K], keepdims=True will lead accuracy larger than 1.0;
For now vis_weights value comes from vis_label.new_ones or dataset visible labels( when shape is [N,K,2]), so vis_weights is always [N,K]. I just delete the keepdims para.
Perhaps I miss some cases?
**Before PR**:
**After PR**:

[Fix] Fix incorrect keepdims in vis_accuracy of vis_head

---

mmpose/visualization/local_visualizer_3d.py

fig.canvas provides float32 data, not uint8. This fixes the issue.
This fixes this issue https://github.com/open-mmlab/mmpose/issues/2816
Fixes the issue where the data is not processed properly
**Before PR**:
**After PR**:

[Fix] Fix to local_visualizer_3d data dumping

---

configs/body_2d_keypoint/rtmpose/body8/rtmpose_body8-coco.yml
configs/wholebody_2d_keypoint/rtmpose/coco-wholebody/rtmpose_coco-wholebody.yml
mmpose/apis/inferencers/utils/default_det_models.py
projects/rtmpose/app.py

[Feature] support RTMPose Gradio app in projects

---

mmpose/visualization/opencv_backend_visualizer.py

This pull request addresses a gap in the `OpencvBackendVisualizer` class's `draw_texts` method. Although the docstring mentions support for "bottom," "top," and "center" alignments, the current implementation lacks the ability to center-align text. This modification aims to rectify this limitation.
I've updated the draw_texts method to support center alignment for both horizontal and vertical positioning.
**Before PR**:
**After PR**:

[Feature] Add center alignments for draw_texts in OpencvBackendVisualizer

---

docs/en/user_guides/train_and_test.md
docs/zh_cn/user_guides/train_and_test.md

Found a mistake/typo in the documentation while following it.
Fixed typo, using PORT for port number instead of GPUS
**Before PR**:
**After PR**:

[Doc] fix typo in training command

---

mmpose/datasets/datasets/wholebody/coco_wholebody_dataset.py

``parse_data_info()`` in ``class CocoWholeBodyDataset`` will return `category_id` as a `List`, making the `transform()` in ``class FilterAnnotations`` fails to **indexing** like a np.array.
make `category_id` as a `numpy.array`, just like what in ``class BaseCocoStyleDataset`` does.
**Before PR**:
**After PR**:

[Fix] make category_id in CocoWholeBodyDataset as numpy.array

---

projects/rtmpose/README.md
projects/rtmpose3d/README.md

[Doc] Update RTMW citation information

---

docs/en/installation.md

Fix a few typos to make it clear for those who is reading it for the first time.
Several typos, such as incorrect tense (e.g., "If you prefer other versions, just modified the Dockerfile").
No
**Before PR**:
Not relevant:
**After PR**:

Fix typos in installation.md
